


function  addSaiName(key,value,data) {
    if (!data[key])
    {
        data[key]= value;
    }else{
        console.log(data[key]);
    }
}

function  getSaiList() {
    let data = {};
    addSaiName("切禾", "基尔禾",data);
    addSaiName("洛达JC", "洛达",data);
    addSaiName("希尔克堡", "施克堡",data);
    addSaiName("阿蘭亞斯堡", "阿兰亚士邦",data);
    addSaiName("多瑙河鲁塞", "多恼",data);
    addSaiName("普夫迪夫火車頭", "普夫迪夫火车头",data);
    addSaiName("亚历山德里亚足球俱乐部", "阿拉卡森德里亚",data);
    addSaiName("圣塞瓦斯蒂安德洛斯雷耶斯", "圣瑟巴斯提安雷耶斯",data);
    addSaiName("伊布罗", "伊波罗",data);
    addSaiName("柯尼拉", "科诺拉",data);
    addSaiName("福门特拉", "福汶特拉",data);
    addSaiName("艾斯查", "艾西加",data);
    addSaiName("毕尔包", "毕尔巴鄂竞技",data);
    addSaiName("S.維尔瓦", "斯波盯维尔瓦",data);
    addSaiName("阿韦亚内达竞赛俱乐部", "竞赛会",data);
    addSaiName("辛特侯逊", "桑德豪森",data);
    addSaiName("卡维哈拉", "科维拉",data);
    addSaiName("維多利亞柏林", "维多利亚柏林",data);
    addSaiName("纳普里达克克鲁舍瓦茨", "纳普里达克",data);
    addSaiName("阿里斯", "阿里斯塞萨洛尼基",data);
    addSaiName("潘塞拉高斯", "邦萨拉高斯",data);
    addSaiName("邦萨拉高斯", "喜百年",data);
    addSaiName("斯洛云布拉迪斯拉发", "斯洛云",data);
    addSaiName("侯布洛", "霍布罗",data);
    addSaiName("曼希恩", "曼海姆",data);
    addSaiName("济拉", "兹拉",data);
    addSaiName("尼菲治", "巴库尼菲治",data);
    addSaiName("Argentinos Juniors", "小阿根廷人",data);
    addSaiName("E.S.撒赫尔", "沙希尔",data);
    addSaiName("史法克斯", "斯法克斯",data);
    addSaiName("埃弗顿", "爱华顿",data);
    addSaiName("费伦迪纳", "费伦天拿",data);
    addSaiName("士柏 2013", "史帕尔",data);
    addSaiName("伊斯坦布尔", "伊斯坦堡希尔",data);
    addSaiName("阿莱森多里亚", "亚力山德利亚",data);
    addSaiName("蒙萨", "蒙扎",data);
    addSaiName("维迪比斯", "维泰贝斯卡",data);
    addSaiName("祖云斯达比亚", "祖华史塔比亚",data);
    addSaiName("清奈泰坦", "清奈因",data);
    addSaiName("艾里斯利馬斯素爾", "艾里斯",data);
    addSaiName("阿尔塔亚文布赖达", "塔亚文布莱达",data);
    addSaiName("伊蒂法克", "伊地法格",data);
    addSaiName("卢高", "卢戈",data);
    addSaiName("波根沙斯辛", "沙斯辛",data);
    addSaiName("维斯瓦克拉科夫", "克拉科夫",data);
    addSaiName("安东米度士", "亚图米图斯",data);
    addSaiName("利瓦迪亚高斯", "利云达高斯",data);
    addSaiName("伊安尼那", "基亚连拿",data);
    addSaiName("拉密亚", "拉米亚",data);
    addSaiName("艾路卡", "阿鲁卡",data);
    addSaiName("歷索斯", "雷克斯欧斯",data);
    addSaiName("歐力維倫斯", "奥利维伦斯",data);
    addSaiName("卡拉奥华", "CS卡拉奥华大学",data);
    addSaiName("马德里竞技", "马德里",data);
    addSaiName("洛桑競技", "洛桑体育",data);
    addSaiName("沃尔夫斯贝格", "禾夫斯堡",data);
    addSaiName("United SC", "联竞技加尔各答",data);
    addSaiName("巴甘莫哈", "莫亨巴根",data);
    addSaiName("托斯諾", "图斯諾",data);
    addSaiName("卡拉布基斯普", "卡拉布克士邦",data);
    addSaiName("布隆迪", "蒲隆地共和国",data);
    addSaiName("加巴拉PFC", "卡巴拉",data);
    addSaiName("南德阿美利加", "苏阿美利加",data);
    addSaiName("罗比沙奇拉夏普尔", "海法罗比沙普拉",data);
    addSaiName("泊列勃理", "柏斯波利斯",data);
    addSaiName("桑納特纳夫特阿巴丹", "纳夫特",data);
    addSaiName("丹蒙迪谢赫", "贾马尔",data);
    addSaiName("尤文提度", "尤文都德彼德拉斯",data);
    addSaiName("保卫者队", "德丰索体育队",data);
    addSaiName("沃伦塔里", "沃鲁塔瑞",data);
    addSaiName("菲伦斯", "费伦斯",data);
    addSaiName("托奧斯", "奧斯",data);
    addSaiName("史查福豪森", "沙夫豪森",data);
    addSaiName("马卡比特拉维夫", "特拉维夫马卡比",data);
    addSaiName("锡耶纳", "若布斯恩纳",data);
    addSaiName("赫罗纳", "基罗纳",data);
    addSaiName("桑塔马里纳", "坦迪尔",data);
    addSaiName("利伯泰德桑查尔斯", "利伯泰迪桑察勒斯",data);
    addSaiName("贝尔格拉诺体育", "斯伯迪沃贝尔格拉诺",data);
    addSaiName("貝爾格拉諾防衛隊若瑪羅", "贝尔格拉诺防卫队若玛罗",data);
    addSaiName("吉姆纳西亚", "甘拿斯亚康塞普森",data);
    addSaiName("卢多格德斯.拉兹格勒", "卢多格瑞特拉兹格勒",data);
    addSaiName("格罗兹尼艾哈迈德", "阿科马特",data);
    addSaiName("阿富拉夏普爾", "阿福拉哈普尔",data);
    addSaiName("拉馬特甘夏普爾", "夏普尔拉马甘吉夫塔伊姆",data);
    addSaiName("克法尔萨巴哈普尔", "法萨巴夏普尔",data);
    addSaiName("RS拜尔坎", "贝尔卡勒",data);
    addSaiName("彼達迪華馬卡比", "彼达迪华马卡比",data);
    addSaiName("斯劳镇", "斯洛格镇",data);
    addSaiName("布萨斯堡", "柏萨士邦",data);
    addSaiName("亚丹纳斯堡", "艾丹拿斯堡",data);
    addSaiName("波卢斯堡", "布鲁斯堡",data);
    addSaiName("特拉布宗斯波尔", "特拉布宗",data);
    addSaiName("埃尔祖鲁姆士邦", "普野社希尔埃尔祖鲁姆士邦",data);
    addSaiName("甘美奧", "甘美奥RS",data);
    addSaiName("乔治罗尼亚比亚韦斯托克", "乔治罗尼亚",data);
    addSaiName("历基亚华沙", "历基亚",data);
    addSaiName("布雷达", "比达",data);
    addSaiName("阿雅克肖加泽莱克", "加泽莱克阿些斯奥",data);
    addSaiName("KAA真特", "真特",data);
    addSaiName("美因玆", "美因茨05",data);
    addSaiName("多蒙特", "多特蒙德",data);
    addSaiName("慕遜加柏", "门兴格拉德巴赫",data);
    addSaiName("尼切萨", "布鲁克贝特马利卡纳斯萨",data);
    addSaiName("斯拉斯克弗罗茨瓦夫", "斯拉斯克",data);
    addSaiName("阿卡格丁尼亚", "阿卡",data);
    addSaiName("伯恩利", "般尼",data);
    addSaiName("布莱克本流浪", "布力般流浪",data);
    addSaiName("卡莱尔", "卡素尔",data);
    addSaiName("埃克塞特", "艾斯特城",data);
    addSaiName("格兰森林", "格连森林",data);
    addSaiName("弗莱德", "菲尔德",data);
    addSaiName("坚士波罗", "真斯布洛治",data);
    addSaiName("乔利", "乔勒伊",data);
    addSaiName("波德诺内", "波代诺内",data);
    addSaiName("艾华尼斯", "恩华利斯",data);
    addSaiName("切尔西", "车路士",data);
    addSaiName("安格斯", "昂热",data);
    addSaiName("AL雷恩", "艾尔雷恩",data);
    addSaiName("USM 阿爾及爾", "USM阿尔格",data);
    addSaiName("大都會警察", "麦罗波利塔诺波利斯",data);
    addSaiName("格茨海德", "凯兹海得",data);
    addSaiName("托基聯", "托基联",data);
    addSaiName("福克斯顿", "佛克斯通",data);
    addSaiName("维森", "沃辛",data);
    addSaiName("Hanwell Town FC ", "汉威尔城",data);
    addSaiName("圣塔克莱拉", "辛达卡拉",data);
    addSaiName("埃尔维斯", "阿维斯",data);
    addSaiName("阿尔贾兹拉阿布扎比", "詹辛拉",data);
    addSaiName("列吉亚格但斯克", "列治亚",data);
    addSaiName("莱赫波茲南", "莱克",data);
    addSaiName("费内巴切", "费伦巴治",data);
    addSaiName("史特加", "斯图加特",data);
    addSaiName("艾比路內費", "艾宾奴列夫",data);
    addSaiName("克拉科维亚克拉科夫", "克拉科夫",data);
    addSaiName("桑德克亚", "桑德西亚",data);
    addSaiName("史浩克零四", "沙尔克04",data);
    addSaiName("阿巴甸", "阿伯丁",data);
    addSaiName("修咸顿", "南安普敦",data);
    addSaiName("李斯特城", "莱斯特城",data);
    addSaiName("史云斯", "斯旺西城",data);
    addSaiName("般尼茅夫", "伯恩茅斯",data);
    addSaiName("特尔斯", "托尔司",data);
     addSaiName("伊斯坦堡", "伊斯坦堡士邦",data);
     addSaiName("班加罗尔", "班加鲁鲁",data);
     addSaiName("史特加Am", "斯图加特青年队",data);
     addSaiName("拉素", "拉齐奥",data);
     addSaiName("乐克雷拉联", "尤尼昂",data);
     addSaiName("悉尼 FC", "悉尼",data);
     addSaiName("恩高斯达", "印戈斯塔德",data);
     addSaiName("贝德邦", "派特博恩",data);
     addSaiName("尼姆斯", "奈梅斯",data);
     addSaiName("艾马", "埃曼",data);
     addSaiName("巴黎足球俱乐部", "巴黎",data);
     addSaiName("保格柏隆拿斯", "布尔格布雷斯普瑞兰斯",data);
     addSaiName("尚布利", "切姆步莱",data);
     addSaiName("哥尔维利", "克维伊鲁昂",data);
     addSaiName("马赛康索拉特", "康索拉特",data);
     addSaiName("阿雅克肖", "阿些斯奧",data);
     addSaiName("阿尔默勒", "阿梅尔城",data);
     addSaiName("查特亚罗斯", "沙特鲁",data);
     addSaiName("苗斯干匹卢维兹", "皇家艾克斯尔梅斯干",data);
     addSaiName("威尼斯", "威尼基亚",data);
     addSaiName("圣伊天", "圣埃蒂安",data);
     addSaiName("巴塞隆拿 B", "巴塞罗那B队",data);
     addSaiName("巴塞隆拿", "巴塞罗那",data);
     addSaiName("西维尔", "塞维利亚",data);
    addSaiName("新城堡聯", "纽卡斯托",data);
    addSaiName("中部海岸海员", "中央海岸",data);
    addSaiName("耶拿", "卡尔斯耶拿",data);
    addSaiName("维尔茨堡", "维尔茨堡踢球者",data);
    addSaiName("梅佩恩", "梅彭",data);
    addSaiName("洛特", "罗塔",data);
    addSaiName("馬格德堡", "马德堡",data);
    addSaiName("苏迪路", "苏达迪罗尔",data);
    addSaiName("艾宾奴列夫", "艾比路內費",data);
    addSaiName("布拉圖", "普拉托",data);
    addSaiName("瓦朗谢讷", "华伦西恩斯",data);
    addSaiName("卡比", "卡皮",data);
    addSaiName("维切利", "维塞利",data);
    addSaiName("克雷特伊", "贾特尔",data);
    addSaiName("毕士图路华", "布里斯托流浪",data);
    addSaiName("里斯本竞技 B", "士砵亭B队",data);
    addSaiName("奥沙辛拿", "奥萨苏纳",data);
    addSaiName("温布顿", "威布雷登",data);
    addSaiName("巴恩斯利", "班士利",data);
    addSaiName("安南競技", "安南体育会",data);
    addSaiName("彼得赫特", "彼得克",data);
    addSaiName("波尔图B队", "波图B队",data);
    addSaiName("布拉德福德公园", "布拉德福德派克大街",data);
    addSaiName("艾迪尔人", "艾积尔奈恩斯",data);
    addSaiName("克森艾斯顿", "柯尔松阿什顿",data);
    addSaiName("科瓦达皮耶达迪", "科瓦皮耶达迪",data);
    addSaiName("伊汀堡", "爱丁堡城",data);
    addSaiName("考文垂", "高云地利",data);
    addSaiName("希美咸史特城", "赫默尔亨普斯特德城",data);
    addSaiName("连高尔", "林肯城",data);
    addSaiName("富咸", "富勒姆",data);
    addSaiName("布莱克浦", "黑池",data);
    addSaiName("洛達咸联", "洛达咸",data);
    addSaiName("锡菲联", "谢菲尔德联",data);
    addSaiName("伊斯特拉1961", "艾斯特拉",data);
    addSaiName("雷乌斯", "瑞厄斯",data);
    addSaiName("哥瑞纳达", "格拉纳达",data);
    addSaiName("拖连奴", "都灵",data);
    addSaiName("伊巴", "埃瓦尔",data);
    addSaiName("赫尔城", "侯城",data);
    addSaiName("雷真亚拿", "雷吉亚那",data);
    addSaiName("锡永", "锡昂",data);
    addSaiName("吉英坎", "甘冈",data);
    addSaiName("马斯梅克林", "梅赫伦",data);
    addSaiName("迪卓恩", "第戎",data);
    addSaiName("科尔多瓦", "哥杜巴",data);
    addSaiName("拉温那", "拉文纳",data);
    addSaiName("西维尔 B队", "塞维利亚竞技",data);
    addSaiName("索尔福德市", "莎尔福德城",data);
    addSaiName("库内奥", "库尼奥1905",data);
    addSaiName("祖云达斯", "尤文图斯",data);
    addSaiName("克罗托内", "克努托内",data);
    addSaiName("森索罗", "萨索洛",data);
    addSaiName("卡坦薩羅", "卡坦萨罗",data);
    addSaiName("柏干尼斯", "帕加尼斯",data);
    addSaiName("格拉兹风暴", "格拉兹",data);
    addSaiName("錫拉庫紮", "锡拉库萨",data);
    addSaiName("法马里绍", "法马利卡欧",data);
    addSaiName("NK 路德斯", "鲁达士",data);
    addSaiName("班尼云度", "班尼文托",data);
    addSaiName("拉斯帕尔马斯", "拉斯彭马斯",data);
    addSaiName("里斯本竞技", "士砵亭",data);
    addSaiName("艾科坎", "阿柯孔",data);
    addSaiName("华历简奴", "瓦莱卡诺",data);
    addSaiName("Keshla FK", "克斯拉",data);
    addSaiName("高阿体育会", "SC果阿",data);
    addSaiName("阿尔阿瓦斯杜拜", "瓦斯尔杜拜",data);
    addSaiName("阿尔瓦赫达阿布扎比", "艾尔维达",data);
    addSaiName("瓦迪格拉", "瓦迪戴加",data);
    addSaiName("阿拉伯康才克托", "阿拉伯建筑",data);
    addSaiName("瓦尔内斯体育生队", "华恩斯体育生",data);
    addSaiName("喀拉拉爆破手", "克瑞拉巴拉斯特斯",data);
    addSaiName("Beitar Ironi Maale Adumim", "比达玛勒阿杜米姆",data);
    addSaiName("阿尔维达特安曼", "威达特安曼",data);
    addSaiName("阿隆頓", "沙巴阿罗登",data);
    addSaiName("卡拜里", "卡比利亚",data);
    addSaiName("尤胡德", "奥赫麦地那",data);
    addSaiName("阿尔沙巴柏利雅德", "沙巴柏利雅德",data);
    addSaiName("伊米瑞特", "酋长",data);
    addSaiName("阿尔阿利吉达", "阿尔艾利吉达",data);
    addSaiName("阿森纳", "阿仙奴",data);
    addSaiName("西汉姆联", "韦斯咸联",data);
    addSaiName("阿尔贝塞特", "阿尔巴塞特",data);
    addSaiName("勒智昂夏普尔", "里雄莱锡安夏普尔耶乌达",data);
    addSaiName("萨哈尼恩", "沙克尼",data);
    addSaiName("丘吉尔兄弟SC", "巴得斯尤",data);
    addSaiName("伊斯梅利", "依斯麦里",data);
    addSaiName("CD Aves", "阿维斯",data);
    addSaiName("玛利比", "莫利比",data);
    addSaiName("拉加競技", "拉加卡萨布兰卡",data);
    addSaiName("加拉法", "阿尔葛拉法",data);
    addSaiName("彼特捷德", "佩特捷德",data);
    addSaiName("PAOK沙朗歷基", "PAOK",data);
    addSaiName("马美洛迪夕阳", "马摩洛迪落日",data);
    addSaiName("Chipstead FC", "奇普斯蒂",data);
    addSaiName("埃格特利斯", "伊高泰利斯",data);
    addSaiName("帕纳基奥斯", "帕纳及勒斯",data);
    addSaiName("Ghivizzano Borgoamozzano", "基维扎诺",data);
    addSaiName("图顿库奥", "图托科约",data);
    addSaiName("Vigor Carpaneto", "维格尔卡尔帕内托",data);
    addSaiName("AC Crema 1908 ASD", "克雷马",data);
    addSaiName("A.C. Trento S.C.S.D.", "特伦托",data);
    addSaiName("體育拉巴特", "FUS拉巴特",data);
    addSaiName("伊蒂哈德伊斯坎达利", "伊蒂哈德亚历山大",data);
    addSaiName("彭拿切基", "帕那洽基",data);
    addSaiName("托瑞莱万特", "多域斯利云特奥瑞欧斯",data);
    addSaiName("Cadiz CF B ", "卡迪斯B队",data);
    addSaiName("阿豪瑞諾", "韦托尔韦加",data);
    addSaiName("布罗凯尔特", "布隆方丹",data);
    addSaiName("超级联盟", "超级联队",data);
    addSaiName("马卡耶", "马卡RJ",data);
    addSaiName("Goytacaz", "哥塔卡扎RJ",data);
    addSaiName("卡柏法伦斯", "康柏费伦斯RJ",data);
    addSaiName("赫塔费", "基达菲",data);
    addSaiName("CD 科瓦东加", "科瓦栋卡",data);
    addSaiName("施斯达奥", "艾尔切艾利塔奴",data);
    addSaiName("伊斯兰教体育俱乐部", "莫哈末丹达卡",data);
    addSaiName("谢赫拉塞尔", "谢克鲁瑟尔",data);
    addSaiName("孟加拉米爾斯", "Team BJMC",data);
    addSaiName("德哈夫拉", "德哈法",data);
    addSaiName("阿积曼", "阿基曼",data);
    addSaiName("拉里萨", "拉瑞沙",data);
    addSaiName("阿纳根尼希", "卡迪",data);
    addSaiName("卡特高皮亚斯", "杜可萨",data);
    addSaiName("卡利地亚雅典", "卡利地亚",data);
    addSaiName("阿尔纳萨杜拜", "纳萨杜拜",data);
    addSaiName("艾恩俱樂部", "艾恩",data);
    addSaiName("塞那乔恩", "SJK塞那乔其",data);
    addSaiName("阿尔卡迪西亚阿克巴", "瓜达席亚",data);
    addSaiName("帕福斯 FC", "帕福斯",data);
    addSaiName("VVSB Noordwijkerhout", "VVSB",data);
    addSaiName("ACD納爾德奧", "纳尔德奥",data);
    addSaiName("波藤紮", "波坦察",data);
    addSaiName("美國队RJ", "美国RJ",data);
    addSaiName("博恩苏塞索", "邦苏塞索RJ",data);
    addSaiName("Indian Arrows", "印地安阿罗",data);
    addSaiName("Gokulam Kerala", "歌库拉姆喀拉拉",data);
    addSaiName("東孟加拉", "翠鸟东孟加拉",data);
    addSaiName("巴萨诺", "巴塞诺",data);
    addSaiName("贝迪斯", "皇家贝迪斯",data);
    addSaiName("西隆拉壮", "拉庄",data);
    addSaiName("安卡拉袓古", "安卡拉高古",data);
    addSaiName("埃米尼奧", "加纳埃米尼奥",data);
    addSaiName("阿科夏普尔", "奥卡哈伯",data);
    addSaiName("德里戴拿模", "德里迪纳摩",data);
    addSaiName("元朗足球會", "元朗",data);
    addSaiName("突尼斯人体育", "史塔德",data);
    addSaiName("尼奈斯加贝斯", "斯塔德加贝申",data);
    addSaiName("阿尔阿利开罗", "阿尔艾利开罗",data);
    addSaiName("约克", "约克城",data);
    addSaiName("修安聯", "修安联",data);
    addSaiName("威靈", "威林联",data);
    addSaiName("达特福德队", "达特福特",data);
    addSaiName("TNS全網絡", "新圣塔斯",data);
    addSaiName("尼威", "瑟傅德鲁迪",data);
    addSaiName("兰迪德诺", "兰杜诺",data);
    addSaiName("巴拉镇", "巴拉城",data);
    addSaiName("诺域治", "诺维奇",data);
    addSaiName("利兹联", "列斯联",data);
    addSaiName("伊普斯维奇城", "伊普斯维奇",data);
    addSaiName("金奈", "金奈城",data);
    addSaiName("基尔史莫纳夏普尔", "伊若尼奇亚夏普尔",data);
    addSaiName("特拉维夫叶胡达", "耶乌达",data);
    addSaiName("托德拉", "通迪拉",data);
    addSaiName("马卡比内坦亚", "马卡比奈坦亚",data);
    addSaiName("寶利", "贝利",data);
    addSaiName("布格斯", "伯吉斯山",data);
    addSaiName("泰沃頓鎮", "特沃顿",data);
    addSaiName("基特宁", "凯特宁",data);
    addSaiName("聖艾夫斯鎮", "史蒂爱文斯城",data);
    addSaiName("尼德姆馬基特", "讷翰马科",data);
    addSaiName("THURROCK FC", "土洛克",data);
    addSaiName("哈云特", "哈文特",data);
    addSaiName("連菲特", "连菲特",data);
    addSaiName("布里斯班", "布里斯班城",data);
    addSaiName("南方联合国", "南方联合",data);
    addSaiName("Gold Coast Knights", "黄金海岸骑士",data);
    addSaiName("布里斯班狼队", "温纳姆狼队",data);
    addSaiName("珀西查雅加达", "佩西加雅加达",data);
    addSaiName("马都拉联队", "马都拉联",data);
    addSaiName("阿提柏", "阿提柏SP",data);
    addSaiName("力亚拿", "尤尼奥隆多诺波利斯",data);
    addSaiName("里奧普雷圖", "里奥沛图SP",data);
    addSaiName("邁拉索爾", "迈拉索尔SP",data);
    addSaiName("阿美利加PE", "美国PE",data);
    addSaiName("马利利亚", "马利利亚SP",data);
    addSaiName("富明尼斯", "富明尼斯RJ",data);
    addSaiName("尤文都德", "尤文都德RS",data);
    addSaiName("裡奧布郎庫 SP", "里奥布郎库SP",data);
    addSaiName("维络", "维罗体育队SP",data);
    addSaiName("隆迪那", "隆迪那PR",data);
    addSaiName("格羅寶", "格罗宝RN",data);
    addSaiName("皮拉西卡巴", "皮拉西卡巴SP",data);
    addSaiName("圣卡坦奴", "圣卡坦奴SP",data);
    addSaiName("裡奧布郎庫", "里奥布朗库AC",data);
    addSaiName("圣本托", "圣本托SP",data);
    addSaiName("保地花高PB", "博塔福格PB",data);
    addSaiName("史特塞特普洛", "塞特普洛AL",data);
    addSaiName("聖安德雷", "圣安德雷SP",data);
    addSaiName("馬杜雷拉", "米底那RJ",data);
    addSaiName("立納瑟", "立纳瑟SP",data);
    addSaiName("帕拉恩瑟PA", "帕拉恩瑟",data);
    addSaiName("费古伦斯", "费古伦斯SC",data);
    addSaiName("巴拉纳", "柏拉拿PR",data);
    addSaiName("图坝奥", "图坝奥SC",data);
    addSaiName("高士路", "高士路MG",data);
    addSaiName("布拉希尔体育", "布拉希尔SP",data);
    addSaiName("彼辛度 PA", "帕桑度PA",data);
    addSaiName("EC皮马维拉", "皮马维拉SP",data);
    addSaiName("EC维托里亚", "维多利亚BA",data);
    addSaiName("伊图阿诺", "伊图阿诺SP",data);
    addSaiName("維拉諾瓦", "维拉诺瓦GO",data);
    addSaiName("哥列迪巴", "哥里迪巴PR",data);
    addSaiName("西尔热", "卡尔拉CE",data);
    addSaiName("巴海尔", "巴海亚BA",data);
    addSaiName("国际队圣保罗AC", "国民队SP",data);
    addSaiName("ABC那托", "ABC RN",data);
    addSaiName("佩纳博伦斯", "佩纳博伦斯SP",data);
    addSaiName("納帝科", "纳帝科PE",data);
    addSaiName("纪柏拉拿", "纪柏拉拿RO",data);
    addSaiName("CE艾莫瑞", "艾莫尔RS",data);
    addSaiName("德陈昭", "雅乌SP",data);
    addSaiName("拉加爾圖SE", "拉加尔图SE",data);
    addSaiName("邦迪比达", "邦迪比达SP",data);
    addSaiName("阿拉沙EC", "阿拉沙MG",data);
    addSaiName("霸塔苔斯", "霸塔苔斯SP",data);
    addSaiName("诺瓦艾夸古", "诺瓦艾夸古RJ",data);
    addSaiName("吉奥競技", "戈亚尼恩斯",data);
    addSaiName("保地花高 SP", "博塔福格SP",data);
    addSaiName("索诺拉", "西玛罗雷斯索诺拉",data);
    addSaiName("阿尔塔德蒙法瓦尼亚", "阿尔塔达孟费瓦尼亚",data);
    addSaiName("萨尔米亚", "沙米亚",data);
    addSaiName("克雷迪", "OFI克雷迪",data);
    addSaiName("奥林比亚高斯", "奥林比亚高斯CFP",data);
    addSaiName("希雷迪亚诺", "希尔迪奥诺",data);
    addSaiName("肯梅利塔", "卡梅利塔",data);
    addSaiName("明尼路", "米内罗竞技",data);
    addSaiName("尼奥特", "尼欧特",data);
    addSaiName("格洛堡", "格洛堡38",data);
    addSaiName("圣诺伊斯", "安坦迪",data);
    addSaiName("康卡纽", "孔卡尔诺",data);
    addSaiName("薩瑟堡", "波城",data);
    addSaiName("肖萊特", "绍莱特",data);
    addSaiName("Cong An Nhan Dan FC", "人民公安",data);
    addSaiName("广宁", "坦广宁",data);
    addSaiName("黃安嘉萊", "归仁",data);
    addSaiName("Ha Noi FC ", "河内",data);
    addSaiName("Binh Dinh", "平定",data);
    addSaiName("胡志明市", "胡志明市足球俱乐部",data);
    addSaiName("Levico Terme", "莱维科泰尔梅",data);
    addSaiName("巴西红牛", "巴西红牛SP",data);
    addSaiName("萨奥 尤涩 RS", "圣乔斯RS",data);
    addSaiName("奥萨斯库奥达斯", "格雷米奥奥萨斯库奥达柯SP",data);
    addSaiName("哥连泰斯", "哥连泰斯SP",data);
    addSaiName("聖瑞蒙度 RR", "圣雷姆恩多RR",data);
    addSaiName("加芬尼卡", "康菲安卡SE",data);
    addSaiName("索卡罗斯", "索卡罗斯SP",data);
    addSaiName("馬蘭瓜佩", "马兰瓜佩CE",data);
    addSaiName("Horizonte CE", "奥里藏特CE",data);
    addSaiName("Guarani de Juazeiro CE", "古兰尼CE",data);
    addSaiName("巴巴朗斯", "巴巴伦斯SP",data);
    addSaiName("里奧布蘭克 ES", "里奥布郎库ES",data);
    addSaiName("赛甘地诺", "萨幹梯诺",data);
    addSaiName("剑鱼队", "多拉多斯",data);
    addSaiName("萨卡特卡斯", "麦拉斯萨卡特卡斯",data);
    addSaiName("泽伦顿", "佩雷斯泽内度",data);
    addSaiName("薩普里薩", "沙普利萨",data);
    addSaiName("桑托斯瓜皮莱斯", "山度士DG",data);
    addSaiName("昆士蘭獅隊", "昆士兰狮队",data);
    addSaiName("阿巴哈尼", "阿坝汉尼度哈卡",data);
    addSaiName("艾斯迪格拿梅里阿瓦", "艾斯迪格拿候萨斯坦",data);
    addSaiName("特黑兰", "德黑兰",data);
    addSaiName("特拉克托", "泰拉克托",data);
    addSaiName("培坎", "派肯",data);
    addSaiName("瑞法", "阿尔瑞法",data);
    addSaiName("东里法", "伊斯特瑞法",data);
    addSaiName("马尔克基亚", "马勒基亚",data);
    addSaiName("阿尔希德", "希德",data);
    addSaiName("瓦拉什斯凱", "梅泽里西",data);
    addSaiName("普斯特喬", "坡斯特乔",data);
    addSaiName("马贝尔拉", "玛贝亚",data);
    addSaiName("阿希亞瓊", "沙迦",data);
    addSaiName("阿尔納斯利雅德", "纳撒利雅德",data);
    addSaiName("阿非哈", "费哈",data);
    addSaiName("法斯", "阿尔菲斯",data);
    addSaiName("特雷泽", "特雷泽PB",data);
    addSaiName("科爾迪諾", "科尔迪诺MA",data);
    addSaiName("国际体育会", "国际体育会RS",data);
    addSaiName("巴拉纳体育会", "帕拉尼恩斯",data);
    addSaiName("沃突普兰古恩斯", "沃图波兰伦斯SP",data);
    addSaiName("基斯奧马", "基斯奥马SC",data);
    addSaiName("卡比华兰奴", "卡皮哇瑞罗SP",data);
    addSaiName("沙佩科恩斯", "乔沛高恩斯SC",data);
    addSaiName("山度士", "山度士SP",data);
    addSaiName("东北联盟", "东北联",data);
    addSaiName("西亚詹美甘", "史拉加梅罕",data);
    addSaiName("阿汉", "紮巴汉",data);
    addSaiName("塞柏", "塞帕卡拉杰",data);
    addSaiName("最卡宾", "泽维卡平联",data);
    addSaiName("Shan United FC", "掸联",data);
    addSaiName("弗列德", "弗兰候萨斯坦",data);
    addSaiName("迪巴铝富查伊拉", "迪巴阿富查伊拉",data);
    addSaiName("荷兹利亚夏普尔", "赫兹立亚马卡比",data);
    addSaiName("阿基纳扎力", "阿基纳紮力马卡比",data);
    addSaiName("Tzeirei Tamra", "提泽雷塔玛拉",data);
    addSaiName("裏桑勒智昂", "纳拉特耶乌达夏普尔",data);
    addSaiName("Shimshon Kfar Qasem", "参孙卡法权瑟姆",data);
    addSaiName("阿尔拉德", "雷德",data);
    addSaiName("沃尔特雷东达", "沃尔特雷东达RJ",data);
    addSaiName("积安维尔", "积安维尔SC",data);
    addSaiName("加菲泰尼洛斯", "卡菲塔勒斯塔帕丘拉",data);
    addSaiName("阿尔阿利多哈", "阿尔艾利多哈",data);
    addSaiName("阿尔阿拉毕多哈", "阿拉毕多哈",data);
    addSaiName("香港飛馬", "香港飞马",data);
    addSaiName("利華戴亞塔林", "雷瓦狄亚",data);
    addSaiName("华露", "华路",data);
    addSaiName("白金星", "铂星",data);
    addSaiName("科帕沃古", "HK科帕沃古",data);
    addSaiName("凯夫拉维卡", "凯夫拉维克",data);
    addSaiName("马斯里", "马萨雷",data);
    addSaiName("Firhouse Clover", "菲浩斯克咯沃尔",data);
    addSaiName("Portmarnock AFC", "波特马诺克",data);
    addSaiName("伊斯頓沙伯", "伊斯特恩沙伯奥克兰",data);
    addSaiName("惠灵顿凤凰", "威灵顿凤凰",data);
    addSaiName("鹰啸联队", "豪克斯湾",data);
    addSaiName("史莫哈", "索莫哈",data);
    addSaiName("FH夏拿佐杜亚", "夏拿佐杜亚",data);
    addSaiName("弗罗瑞安娜FC", "佛罗里亚纳",data);
    addSaiName("希伯尼恩斯", "喜柏尼恩斯波拉",data);
    addSaiName("El-Kanemi Warriors", "卡尼米勇士",data);
    addSaiName("高顿", "金箭",data);
    addSaiName("华特斯", "拜维思",data);
    addSaiName("Rockmount AFC", "洛克茂",data);
    addSaiName("University College Cork AFC", "科克大学学院",data);
    addSaiName("巴塞隆拿瓜亚基尔", "巴塞隆拿SC",data);

    return data;
}

let AddData = {
    getSaiList:getSaiList,
};

module.exports =  AddData;