


function  addSaiName(key,value,data) {
    key = key.trim();
    value =value.trim();
    if (!data[key])
    {
        data[key]= value;
    }else{
        console.log(data[key]);
    }
}

function  getSaiList() {
    let data = {};
    addSaiName("切禾", "基尔禾",data);
    addSaiName("洛达JC", "洛达",data);
    addSaiName("希尔克堡", "施克堡",data);
    addSaiName("阿蘭亞斯堡", "阿兰亚士邦",data);
    addSaiName("多瑙河鲁塞", "多恼",data);
    addSaiName("普夫迪夫火車頭", "普夫迪夫火车头",data);
    addSaiName("亚历山德里亚足球俱乐部", "阿拉卡森德里亚",data);
    addSaiName("圣塞瓦斯蒂安德洛斯雷耶斯", "圣瑟巴斯提安雷耶斯",data);
    addSaiName("伊布罗", "伊波罗",data);
    addSaiName("柯尼拉", "科诺拉",data);
    addSaiName("福门特拉", "福汶特拉",data);
    addSaiName("艾斯查", "艾西加",data);
    addSaiName("毕尔包", "毕尔巴鄂竞技",data);
    addSaiName("S.維尔瓦", "斯波盯维尔瓦",data);
    addSaiName("阿韦亚内达竞赛俱乐部", "竞赛会",data);
    addSaiName("辛特侯逊", "桑德豪森",data);
    addSaiName("卡维哈拉", "科维拉",data);
    addSaiName("維多利亞柏林", "维多利亚柏林",data);
    addSaiName("纳普里达克克鲁舍瓦茨", "纳普里达克",data);
    addSaiName("阿里斯", "阿里斯塞萨洛尼基",data);
    addSaiName("潘塞拉高斯", "邦萨拉高斯",data);
    addSaiName("邦萨拉高斯", "喜百年",data);
    addSaiName("斯洛云布拉迪斯拉发", "斯洛云",data);
    addSaiName("侯布洛", "霍布罗",data);
    addSaiName("曼希恩", "曼海姆",data);
    addSaiName("济拉", "兹拉",data);
    addSaiName("尼菲治", "巴库尼菲治",data);
    addSaiName("Argentinos Juniors", "小阿根廷人",data);
    addSaiName("E.S.撒赫尔", "沙希尔",data);
    addSaiName("史法克斯", "斯法克斯",data);
    addSaiName("埃弗顿", "爱华顿",data);
    addSaiName("费伦迪纳", "费伦天拿",data);
    addSaiName("士柏 2013", "史帕尔",data);
    addSaiName("伊斯坦布尔", "伊斯坦堡希尔",data);
    addSaiName("阿莱森多里亚", "亚力山德利亚",data);
    addSaiName("蒙萨", "蒙扎",data);
    addSaiName("维迪比斯", "维泰贝斯卡斯特伦斯",data);
    addSaiName("祖云斯达比亚", "祖华史塔比亚",data);
    addSaiName("清奈泰坦", "清奈因",data);
    addSaiName("艾里斯利馬斯素爾", "艾里斯",data);
    addSaiName("阿尔塔亚文布赖达", "塔亚文布莱达",data);
    addSaiName("伊蒂法克", "伊地法格",data);
    addSaiName("卢高", "卢戈",data);
    addSaiName("波根沙斯辛", "沙斯辛",data);
    addSaiName("维斯瓦克拉科夫", "克拉科夫",data);
    addSaiName("安东米度士", "亚图米图斯",data);
    addSaiName("利瓦迪亚高斯", "利云达高斯",data);
    addSaiName("伊安尼那", "基亚连拿",data);
    addSaiName("拉密亚", "拉米亚",data);
    addSaiName("艾路卡", "阿鲁卡",data);
    addSaiName("歷索斯", "雷克斯欧斯",data);
    addSaiName("歐力維倫斯", "奥利维伦斯",data);
    addSaiName("卡拉奥华", "CS卡拉奥华大学",data);
    addSaiName("马德里竞技", "马德里",data);
    addSaiName("洛桑競技", "洛桑体育",data);
    addSaiName("沃尔夫斯贝格", "禾夫斯堡",data);
    addSaiName("United SC", "联竞技加尔各答",data);
    addSaiName("巴甘莫哈", "莫亨巴根",data);
    addSaiName("托斯諾", "图斯諾",data);
    addSaiName("卡拉布基斯普", "卡拉布克士邦",data);
    addSaiName("布隆迪", "蒲隆地共和国",data);
    addSaiName("加巴拉PFC", "卡巴拉",data);
    addSaiName("南德阿美利加", "苏阿美利加",data);
    addSaiName("罗比沙奇拉夏普尔", "海法罗比沙普拉",data);
    addSaiName("泊列勃理", "柏斯波利斯",data);
    addSaiName("桑納特纳夫特阿巴丹", "纳夫特",data);
    addSaiName("丹蒙迪谢赫", "贾马尔",data);
    addSaiName("尤文提度", "尤文都德彼德拉斯",data);
    addSaiName("保卫者队", "德丰索体育队",data);
    addSaiName("沃伦塔里", "沃鲁塔瑞",data);
    addSaiName("菲伦斯", "费伦斯",data);
    addSaiName("托奧斯", "奧斯",data);
    addSaiName("史查福豪森", "沙夫豪森",data);
    addSaiName("马卡比特拉维夫", "特拉维夫马卡比",data);
    addSaiName("锡耶纳", "若布斯恩纳",data);
    addSaiName("赫罗纳", "基罗纳",data);
    addSaiName("桑塔马里纳", "坦迪尔",data);
    addSaiName("利伯泰德桑查尔斯", "利伯泰迪桑察勒斯",data);
    addSaiName("贝尔格拉诺体育", "斯伯迪沃贝尔格拉诺",data);
    addSaiName("貝爾格拉諾防衛隊若瑪羅", "贝尔格拉诺防卫队若玛罗",data);
    addSaiName("吉姆纳西亚", "甘拿斯亚康塞普森",data);
    addSaiName("卢多格德斯.拉兹格勒", "卢多格瑞特拉兹格勒",data);
    addSaiName("格罗兹尼艾哈迈德", "阿科马特",data);
    addSaiName("阿富拉夏普爾", "阿福拉哈普尔",data);
    addSaiName("拉馬特甘夏普爾", "夏普尔拉马甘吉夫塔伊姆",data);
    addSaiName("克法尔萨巴哈普尔", "法萨巴夏普尔",data);
    addSaiName("RS拜尔坎", "贝尔卡勒",data);
    addSaiName("彼達迪華馬卡比", "彼达迪华马卡比",data);
    addSaiName("斯劳镇", "斯洛格镇",data);
    addSaiName("布萨斯堡", "柏萨士邦",data);
    addSaiName("亚丹纳斯堡", "艾丹拿斯堡",data);
    addSaiName("波卢斯堡", "布鲁斯堡",data);
    addSaiName("特拉布宗斯波尔", "特拉布宗",data);
    addSaiName("埃尔祖鲁姆士邦", "普野社希尔埃尔祖鲁姆士邦",data);
    addSaiName("甘美奧", "甘美奥RS",data);
    addSaiName("乔治罗尼亚比亚韦斯托克", "乔治罗尼亚",data);
    addSaiName("历基亚华沙", "历基亚",data);
    addSaiName("布雷达", "比达",data);
    addSaiName("阿雅克肖加泽莱克", "加泽莱克阿些斯奥",data);
    addSaiName("KAA真特", "真特",data);
    addSaiName("美因玆", "美因茨05",data);
    addSaiName("多蒙特", "多特蒙德",data);
    addSaiName("慕遜加柏", "门兴格拉德巴赫",data);
    addSaiName("尼切萨", "布鲁克贝特马利卡纳斯萨",data);
    addSaiName("斯拉斯克弗罗茨瓦夫", "斯拉斯克",data);
    addSaiName("阿卡格丁尼亚", "阿卡",data);
    addSaiName("伯恩利", "般尼",data);
    addSaiName("布莱克本流浪", "布力般流浪",data);
    addSaiName("卡莱尔", "卡素尔",data);
    addSaiName("埃克塞特", "艾斯特城",data);
    addSaiName("格兰森林", "格连森林",data);
    addSaiName("弗莱德", "菲尔德",data);
    addSaiName("坚士波罗", "真斯布洛治",data);
    addSaiName("乔利", "乔勒伊",data);
    addSaiName("波德诺内", "波代诺内",data);
    addSaiName("艾华尼斯", "恩华利斯",data);
    addSaiName("切尔西", "车路士",data);
    addSaiName("安格斯", "昂热",data);
    addSaiName("AL雷恩", "艾尔雷恩",data);
    addSaiName("USM 阿爾及爾", "USM阿尔格",data);
    addSaiName("大都會警察", "麦罗波利塔诺波利斯",data);
    addSaiName("格茨海德", "凯兹海得",data);
    addSaiName("托基聯", "托基联",data);
    addSaiName("福克斯顿", "佛克斯通",data);
    addSaiName("维森", "沃辛",data);
    addSaiName("Hanwell Town FC ", "汉威尔城",data);
    addSaiName("圣塔克莱拉", "辛达卡拉",data);
    addSaiName("埃尔维斯", "阿维斯",data);
    addSaiName("阿尔贾兹拉阿布扎比", "詹辛拉",data);
    addSaiName("列吉亚格但斯克", "列治亚",data);
    addSaiName("莱赫波茲南", "莱克",data);
    addSaiName("费内巴切", "费伦巴治",data);
    addSaiName("史特加", "斯图加特",data);
    addSaiName("艾比路內費", "艾宾奴列夫",data);
    addSaiName("桑德克亚", "桑德西亚",data);
    addSaiName("史浩克零四", "沙尔克04",data);
    addSaiName("阿巴甸", "阿伯丁",data);
    addSaiName("修咸顿", "南安普敦",data);
    addSaiName("李斯特城", "莱斯特城",data);
    addSaiName("史云斯", "斯旺西城",data);
    addSaiName("般尼茅夫", "伯恩茅斯",data);
    addSaiName("特尔斯", "托尔司",data);
     addSaiName("伊斯坦堡", "伊斯坦堡士邦",data);
     addSaiName("班加罗尔", "班加鲁鲁",data);
     addSaiName("史特加Am", "斯图加特青年队",data);
     addSaiName("拉素", "拉齐奥",data);
     addSaiName("乐克雷拉联", "尤尼昂",data);
     addSaiName("悉尼 FC", "悉尼",data);
     addSaiName("恩高斯达", "印戈斯塔德",data);
     addSaiName("贝德邦", "派特博恩",data);
     addSaiName("尼姆斯", "奈梅斯",data);
     addSaiName("艾马", "埃曼",data);
     addSaiName("巴黎足球俱乐部", "巴黎",data);
     addSaiName("保格柏隆拿斯", "布尔格布雷斯普瑞兰斯",data);
     addSaiName("尚布利", "切姆步莱",data);
     addSaiName("哥尔维利", "克维伊鲁昂",data);
     addSaiName("马赛康索拉特", "康索拉特",data);
     addSaiName("阿雅克肖", "阿些斯奧",data);
     addSaiName("阿尔默勒", "阿梅尔城",data);
     addSaiName("查特亚罗斯", "沙特鲁",data);
     addSaiName("苗斯干匹卢维兹", "皇家艾克斯尔梅斯干",data);
     addSaiName("威尼斯", "威尼基亚",data);
     addSaiName("圣伊天", "圣埃蒂安",data);
     addSaiName("巴塞隆拿 B", "巴塞罗那B队",data);
     addSaiName("巴塞隆拿", "巴塞罗那",data);
     addSaiName("西维尔", "塞维利亚",data);
    addSaiName("新城堡聯", "纽卡斯托",data);
    addSaiName("中部海岸海员", "中央海岸",data);
    addSaiName("耶拿", "卡尔斯耶拿",data);
    addSaiName("维尔茨堡", "维尔茨堡踢球者",data);
    addSaiName("梅佩恩", "梅彭",data);
    addSaiName("洛特", "罗塔",data);
    addSaiName("馬格德堡", "马德堡",data);
    addSaiName("苏迪路", "苏达迪罗尔",data);
    addSaiName("艾宾奴列夫", "艾比路內費",data);
    addSaiName("布拉圖", "普拉托",data);
    addSaiName("瓦朗谢讷", "华伦西恩斯",data);
    addSaiName("卡比", "卡皮",data);
    addSaiName("维切利", "维塞利",data);
    addSaiName("克雷特伊", "贾特尔",data);
    addSaiName("毕士图路华", "布里斯托流浪",data);
    addSaiName("里斯本竞技 B", "士砵亭B队",data);
    addSaiName("奥沙辛拿", "奥萨苏纳",data);
    addSaiName("温布顿", "威布雷登",data);
    addSaiName("巴恩斯利", "班士利",data);
    addSaiName("安南競技", "安南体育会",data);
    addSaiName("彼得赫特", "彼得克",data);
    addSaiName("波尔图B队", "波图B队",data);
    addSaiName("布拉德福德公园", "布拉德福德派克大街",data);
    addSaiName("艾迪尔人", "艾积尔奈恩斯",data);
    addSaiName("克森艾斯顿", "柯尔松阿什顿",data);
    addSaiName("科瓦达皮耶达迪", "科瓦皮耶达迪",data);
    addSaiName("伊汀堡", "爱丁堡城",data);
    addSaiName("考文垂", "高云地利",data);
    addSaiName("希美咸史特城", "赫默尔亨普斯特德城",data);
    addSaiName("连高尔", "林肯城",data);
    addSaiName("富咸", "富勒姆",data);
    addSaiName("布莱克浦", "黑池",data);
    addSaiName("洛達咸联", "洛达咸",data);
    addSaiName("锡菲联", "谢菲尔德联",data);
    addSaiName("伊斯特拉1961", "艾斯特拉",data);
    addSaiName("雷乌斯", "瑞厄斯",data);
    addSaiName("哥瑞纳达", "格拉纳达",data);
    addSaiName("拖连奴", "都灵",data);
    addSaiName("伊巴", "埃瓦尔",data);
    addSaiName("赫尔城", "侯城",data);
    addSaiName("雷真亚拿", "雷吉亚那",data);
    addSaiName("锡永", "锡昂",data);
    addSaiName("吉英坎", "甘冈",data);
    addSaiName("马斯梅克林", "梅赫伦",data);
    addSaiName("科尔多瓦", "哥杜巴",data);
    addSaiName("拉温那", "拉文纳",data);
    addSaiName("西维尔 B队", "塞维利亚竞技",data);
    addSaiName("索尔福德市", "莎尔福德城",data);
    addSaiName("库内奥", "库尼奥1905",data);
    addSaiName("祖云达斯", "尤文图斯",data);
    addSaiName("克罗托内", "克努托内",data);
    addSaiName("森索罗", "萨索洛",data);
    addSaiName("卡坦薩羅", "卡坦萨罗",data);
    addSaiName("柏干尼斯", "帕加尼斯",data);
    addSaiName("格拉兹风暴", "格拉兹",data);
    addSaiName("錫拉庫紮", "锡拉库萨",data);
    addSaiName("法马里绍", "法马利卡欧",data);
    addSaiName("NK 路德斯", "鲁达士",data);
    addSaiName("班尼云度", "班尼文托",data);
    addSaiName("拉斯帕尔马斯", "拉斯彭马斯",data);
    addSaiName("里斯本竞技", "士砵亭",data);
    addSaiName("艾科坎", "阿柯孔",data);
    addSaiName("华历简奴", "瓦莱卡诺",data);
    addSaiName("Keshla FK", "克斯拉",data);
    addSaiName("高阿体育会", "SC果阿",data);
    addSaiName("阿尔阿瓦斯杜拜", "瓦斯尔杜拜",data);
    addSaiName("阿尔瓦赫达阿布扎比", "艾尔维达",data);
    addSaiName("瓦迪格拉", "瓦迪戴加",data);
    addSaiName("阿拉伯康才克托", "阿拉伯建筑",data);
    addSaiName("瓦尔内斯体育生队", "华恩斯体育生",data);
    addSaiName("喀拉拉爆破手", "克瑞拉巴拉斯特斯",data);
    addSaiName("Beitar Ironi Maale Adumim", "比达玛勒阿杜米姆",data);
    addSaiName("阿尔维达特安曼", "威达特安曼",data);
    addSaiName("阿隆頓", "沙巴阿罗登",data);
    addSaiName("卡拜里", "卡比利亚",data);
    addSaiName("尤胡德", "奥赫麦地那",data);
    addSaiName("阿尔沙巴柏利雅德", "沙巴柏利雅德",data);
    addSaiName("伊米瑞特", "酋长",data);
    addSaiName("阿尔阿利吉达", "阿尔艾利吉达",data);
    addSaiName("阿森纳", "阿仙奴",data);
    addSaiName("西汉姆联", "韦斯咸联",data);
    addSaiName("阿尔贝塞特", "阿尔巴塞特",data);
    addSaiName("勒智昂夏普尔", "里雄莱锡安夏普尔耶乌达",data);
    addSaiName("萨哈尼恩", "沙克尼",data);
    addSaiName("丘吉尔兄弟SC", "巴得斯尤",data);
    addSaiName("伊斯梅利", "依斯麦里",data);
    addSaiName("CD Aves", "阿维斯",data);
    addSaiName("玛利比", "莫利比",data);
    addSaiName("拉加競技", "拉加卡萨布兰卡",data);
    addSaiName("加拉法", "阿尔葛拉法",data);
    addSaiName("彼特捷德", "佩特捷德",data);
    addSaiName("PAOK沙朗歷基", "PAOK",data);
    addSaiName("马美洛迪夕阳", "马摩洛迪落日",data);
    addSaiName("Chipstead FC", "奇普斯蒂",data);
    addSaiName("埃格特利斯", "伊高泰利斯",data);
    addSaiName("帕纳基奥斯", "帕纳及勒斯",data);
    addSaiName("Ghivizzano Borgoamozzano", "基维扎诺",data);
    addSaiName("图顿库奥", "图托科约",data);
    addSaiName("Vigor Carpaneto", "维格尔卡尔帕内托",data);
    addSaiName("AC Crema 1908 ASD", "克雷马",data);
    addSaiName("A.C. Trento S.C.S.D.", "特伦托",data);
    addSaiName("體育拉巴特", "FUS拉巴特",data);
    addSaiName("伊蒂哈德伊斯坎达利", "伊蒂哈德亚历山大",data);
    addSaiName("彭拿切基", "帕那洽基",data);
    addSaiName("托瑞莱万特", "多域斯利云特奥瑞欧斯",data);
    addSaiName("Cadiz CF B ", "卡迪斯B队",data);
    addSaiName("阿豪瑞諾", "韦托尔韦加",data);
    addSaiName("布罗凯尔特", "布隆方丹",data);
    addSaiName("超级联盟", "超级联队",data);
    addSaiName("马卡耶", "马卡RJ",data);
    addSaiName("Goytacaz", "哥塔卡扎RJ",data);
    addSaiName("卡柏法伦斯", "康柏费伦斯RJ",data);
    addSaiName("赫塔费", "基达菲",data);
    addSaiName("CD 科瓦东加", "科瓦栋卡",data);
    addSaiName("施斯达奥", "艾尔切艾利塔奴",data);
    addSaiName("伊斯兰教体育俱乐部", "莫哈末丹达卡",data);
    addSaiName("谢赫拉塞尔", "谢克鲁瑟尔",data);
    addSaiName("孟加拉米爾斯", "Team BJMC",data);
    addSaiName("德哈夫拉", "德哈法",data);
    addSaiName("阿积曼", "阿基曼",data);
    addSaiName("拉里萨", "拉瑞沙",data);
    addSaiName("阿纳根尼希", "卡迪",data);
    addSaiName("卡特高皮亚斯", "杜可萨",data);
    addSaiName("卡利地亚雅典", "卡利地亚",data);
    addSaiName("阿尔纳萨杜拜", "纳萨杜拜",data);
    addSaiName("艾恩俱樂部", "艾恩",data);
    addSaiName("塞那乔恩", "SJK塞那乔其",data);
    addSaiName("阿尔卡迪西亚阿克巴", "瓜达席亚",data);
    addSaiName("帕福斯 FC", "帕福斯",data);
    addSaiName("VVSB Noordwijkerhout", "VVSB",data);
    addSaiName("ACD納爾德奧", "纳尔德奥",data);
    addSaiName("波藤紮", "波坦察",data);
    addSaiName("美國队RJ", "美国RJ",data);
    addSaiName("博恩苏塞索", "邦苏塞索RJ",data);
    addSaiName("Indian Arrows", "印地安阿罗",data);
    addSaiName("Gokulam Kerala", "歌库拉姆喀拉拉",data);
    addSaiName("東孟加拉", "翠鸟东孟加拉",data);
    addSaiName("巴萨诺", "巴塞诺",data);
    addSaiName("贝迪斯", "皇家贝迪斯",data);
    addSaiName("西隆拉壮", "拉庄",data);
    addSaiName("安卡拉袓古", "安卡拉高古",data);
    addSaiName("埃米尼奧", "加纳埃米尼奥",data);
    addSaiName("阿科夏普尔", "奥卡哈伯",data);
    addSaiName("德里戴拿模", "德里迪纳摩",data);
    addSaiName("元朗足球會", "元朗",data);
    addSaiName("突尼斯人体育", "史塔德",data);
    addSaiName("尼奈斯加贝斯", "斯塔德加贝申",data);
    addSaiName("阿尔阿利开罗", "阿尔艾利开罗",data);
    addSaiName("约克", "约克城",data);
    addSaiName("修安聯", "修安联",data);
    addSaiName("威靈", "威林联",data);
    addSaiName("达特福德队", "达特福特",data);
    addSaiName("TNS全網絡", "新圣塔斯",data);
    addSaiName("尼威", "瑟傅德鲁迪",data);
    addSaiName("兰迪德诺", "兰杜诺",data);
    addSaiName("巴拉镇", "巴拉城",data);
    addSaiName("诺域治", "诺维奇",data);
    addSaiName("利兹联", "列斯联",data);
    addSaiName("伊普斯维奇城", "伊普斯维奇",data);
    addSaiName("金奈", "金奈城",data);
    addSaiName("基尔史莫纳夏普尔", "伊若尼奇亚夏普尔",data);
    addSaiName("特拉维夫叶胡达", "耶乌达",data);
    addSaiName("托德拉", "通迪拉",data);
    addSaiName("马卡比内坦亚", "马卡比奈坦亚",data);
    addSaiName("寶利", "贝利",data);
    addSaiName("布格斯", "伯吉斯山",data);
    addSaiName("泰沃頓鎮", "特沃顿",data);
    addSaiName("基特宁", "凯特宁",data);
    addSaiName("聖艾夫斯鎮", "史蒂爱文斯城",data);
    addSaiName("尼德姆馬基特", "讷翰马科",data);
    addSaiName("THURROCK FC", "土洛克",data);
    addSaiName("哈云特", "哈文特",data);
    addSaiName("連菲特", "连菲特",data);
    addSaiName("布里斯班", "布里斯班城",data);
    addSaiName("南方联合国", "南方联合",data);
    addSaiName("Gold Coast Knights", "黄金海岸骑士",data);
    addSaiName("布里斯班狼队", "温纳姆狼队",data);
    addSaiName("珀西查雅加达", "佩西加雅加达",data);
    addSaiName("马都拉联队", "马都拉联",data);
    addSaiName("阿提柏", "阿提柏SP",data);
    addSaiName("力亚拿", "尤尼奥隆多诺波利斯",data);
    addSaiName("里奧普雷圖", "里奥沛图SP",data);
    addSaiName("邁拉索爾", "迈拉索尔SP",data);
    addSaiName("阿美利加PE", "美国PE",data);
    addSaiName("马利利亚", "马利利亚SP",data);
    addSaiName("富明尼斯", "富明尼斯RJ",data);
    addSaiName("尤文都德", "尤文都德RS",data);
    addSaiName("裡奧布郎庫 SP", "里奥布郎库SP",data);
    addSaiName("维络", "维罗体育队SP",data);
    addSaiName("隆迪那", "隆迪那PR",data);
    addSaiName("格羅寶", "格罗宝RN",data);
    addSaiName("皮拉西卡巴", "皮拉西卡巴SP",data);
    addSaiName("圣卡坦奴", "圣卡坦奴SP",data);
    addSaiName("裡奧布郎庫", "里奥布朗库AC",data);
    addSaiName("圣本托", "圣本托SP",data);
    addSaiName("保地花高PB", "博塔福格PB",data);
    addSaiName("史特塞特普洛", "塞特普洛AL",data);
    addSaiName("聖安德雷", "圣安德雷SP",data);
    addSaiName("馬杜雷拉", "米底那RJ",data);
    addSaiName("立納瑟", "立纳瑟SP",data);
    addSaiName("帕拉恩瑟PA", "帕拉恩瑟",data);
    addSaiName("费古伦斯", "费古伦斯SC",data);
    addSaiName("巴拉纳", "柏拉拿PR",data);
    addSaiName("图坝奥", "图坝奥SC",data);
    addSaiName("高士路", "高士路MG",data);
    addSaiName("布拉希尔体育", "布拉希尔SP",data);
    addSaiName("彼辛度 PA", "帕桑度PA",data);
    addSaiName("EC皮马维拉", "皮马维拉SP",data);
    addSaiName("EC维托里亚", "维多利亚BA",data);
    addSaiName("伊图阿诺", "伊图阿诺SP",data);
    addSaiName("維拉諾瓦", "维拉诺瓦GO",data);
    addSaiName("哥列迪巴", "哥里迪巴PR",data);
    addSaiName("西尔热", "卡尔拉CE",data);
    addSaiName("巴海尔", "巴海亚BA",data);
    addSaiName("国际队圣保罗AC", "国民队SP",data);
    addSaiName("佩纳博伦斯", "佩纳博伦斯SP",data);
    addSaiName("納帝科", "纳帝科PE",data);
    addSaiName("纪柏拉拿", "纪柏拉拿RO",data);
    addSaiName("CE艾莫瑞", "艾莫尔RS",data);
    addSaiName("德陈昭", "雅乌SP",data);
    addSaiName("拉加爾圖SE", "拉加尔图SE",data);
    addSaiName("邦迪比达", "邦迪比达SP",data);
    addSaiName("阿拉沙EC", "阿拉沙MG",data);
    addSaiName("霸塔苔斯", "霸塔苔斯SP",data);
    addSaiName("诺瓦艾夸古", "诺瓦艾夸古RJ",data);
    addSaiName("吉奥競技", "戈亚尼恩斯",data);
    addSaiName("保地花高 SP", "博塔福格SP",data);
    addSaiName("索诺拉", "西玛罗雷斯索诺拉",data);
    addSaiName("阿尔塔德蒙法瓦尼亚", "阿尔塔达孟费瓦尼亚",data);
    addSaiName("萨尔米亚", "沙米亚",data);
    addSaiName("克雷迪", "OFI克雷迪",data);
    addSaiName("奥林比亚高斯", "奥林比亚高斯CFP",data);
    addSaiName("希雷迪亚诺", "希尔迪奥诺",data);
    addSaiName("肯梅利塔", "卡梅利塔",data);
    addSaiName("明尼路", "米内罗竞技",data);
    addSaiName("尼奥特", "尼欧特",data);
    addSaiName("格洛堡", "格洛堡38",data);
    addSaiName("圣诺伊斯", "安坦迪",data);
    addSaiName("康卡纽", "孔卡尔诺",data);
    addSaiName("薩瑟堡", "波城",data);
    addSaiName("肖萊特", "绍莱特",data);
    addSaiName("Cong An Nhan Dan FC", "人民公安",data);
    addSaiName("广宁", "坦广宁",data);
    addSaiName("黃安嘉萊", "归仁",data);
    addSaiName("Ha Noi FC ", "河内",data);
    addSaiName("Binh Dinh", "平定",data);
    addSaiName("胡志明市", "胡志明市足球俱乐部",data);
    addSaiName("Levico Terme", "莱维科泰尔梅",data);
    addSaiName("巴西红牛", "巴西红牛SP",data);
    addSaiName("萨奥 尤涩 RS", "圣乔斯RS",data);
    addSaiName("奥萨斯库奥达斯", "格雷米奥奥萨斯库奥达柯SP",data);
    addSaiName("哥连泰斯", "哥连泰斯SP",data);
    addSaiName("聖瑞蒙度 RR", "圣雷姆恩多RR",data);
    addSaiName("加芬尼卡", "康菲安卡SE",data);
    addSaiName("索卡罗斯", "索卡罗斯SP",data);
    addSaiName("馬蘭瓜佩", "马兰瓜佩CE",data);
    addSaiName("Horizonte CE", "奥里藏特CE",data);
    addSaiName("Guarani de Juazeiro CE", "古兰尼CE",data);
    addSaiName("巴巴朗斯", "巴巴伦斯SP",data);
    addSaiName("里奧布蘭克 ES", "里奥布郎库ES",data);
    addSaiName("赛甘地诺", "萨干梯诺",data);
    addSaiName("剑鱼队", "多拉多斯",data);
    addSaiName("萨卡特卡斯", "麦拉斯萨卡特卡斯",data);
    addSaiName("泽伦顿", "佩雷斯泽内度",data);
    addSaiName("薩普里薩", "沙普利萨",data);
    addSaiName("桑托斯瓜皮莱斯", "山度士DG",data);
    addSaiName("昆士蘭獅隊", "昆士兰狮队",data);
    addSaiName("阿巴哈尼", "阿坝汉尼度哈卡",data);
    addSaiName("艾斯迪格拿梅里阿瓦", "艾斯迪格拿候萨斯坦",data);
    addSaiName("特黑兰", "德黑兰",data);
    addSaiName("特拉克托", "泰拉克托",data);
    addSaiName("培坎", "派肯",data);
    addSaiName("瑞法", "阿尔瑞法",data);
    addSaiName("东里法", "伊斯特瑞法",data);
    addSaiName("马尔克基亚", "马勒基亚",data);
    addSaiName("阿尔希德", "希德",data);
    addSaiName("瓦拉什斯凱", "梅泽里西",data);
    addSaiName("普斯特喬", "坡斯特乔",data);
    addSaiName("马贝尔拉", "玛贝亚",data);
    addSaiName("阿希亞瓊", "沙迦",data);
    addSaiName("阿尔納斯利雅德", "纳撒利雅德",data);
    addSaiName("阿非哈", "费哈",data);
    addSaiName("法斯", "阿尔菲斯",data);
    addSaiName("特雷泽", "特雷泽PB",data);
    addSaiName("科爾迪諾", "科尔迪诺MA",data);
    addSaiName("国际体育会", "国际体育会RS",data);
    addSaiName("巴拉纳体育会", "帕拉尼恩斯",data);
    addSaiName("沃突普兰古恩斯", "沃图波兰伦斯SP",data);
    addSaiName("基斯奧马", "基斯奥马SC",data);
    addSaiName("卡比华兰奴", "卡皮哇瑞罗SP",data);
    addSaiName("沙佩科恩斯", "乔沛高恩斯SC",data);
    addSaiName("山度士", "山度士SP",data);
    addSaiName("东北联盟", "东北联",data);
    addSaiName("西亚詹美甘", "史拉加梅罕",data);
    addSaiName("阿汉", "紮巴汉",data);
    addSaiName("塞柏", "塞帕卡拉杰",data);
    addSaiName("最卡宾", "泽维卡平联",data);
    addSaiName("Shan United FC", "掸联",data);
    addSaiName("弗列德", "弗兰候萨斯坦",data);
    addSaiName("迪巴铝富查伊拉", "迪巴阿富查伊拉",data);
    addSaiName("荷兹利亚夏普尔", "赫兹立亚马卡比",data);
    addSaiName("阿基纳扎力", "阿基纳紮力马卡比",data);
    addSaiName("Tzeirei Tamra", "提泽雷塔玛拉",data);
    addSaiName("裏桑勒智昂", "纳拉特耶乌达夏普尔",data);
    addSaiName("Shimshon Kfar Qasem", "参孙卡法权瑟姆",data);
    addSaiName("阿尔拉德", "雷德",data);
    addSaiName("沃尔特雷东达", "沃尔特雷东达RJ",data);
    addSaiName("积安维尔", "积安维尔SC",data);
    addSaiName("加菲泰尼洛斯", "卡菲塔勒斯塔帕丘拉",data);
    addSaiName("阿尔阿利多哈", "阿尔艾利多哈",data);
    addSaiName("阿尔阿拉毕多哈", "阿拉毕多哈",data);
    addSaiName("香港飛馬", "香港飞马",data);
    addSaiName("利華戴亞塔林", "雷瓦狄亚",data);
    addSaiName("华露", "华路",data);
    addSaiName("白金星", "铂星",data);
    addSaiName("科帕沃古", "HK科帕沃古",data);
    addSaiName("凯夫拉维卡", "凯夫拉维克",data);
    addSaiName("马斯里", "马萨雷",data);
    addSaiName("Firhouse Clover", "菲浩斯克咯沃尔",data);
    addSaiName("Portmarnock AFC", "波特马诺克",data);
    addSaiName("伊斯頓沙伯", "伊斯特恩沙伯奥克兰",data);
    addSaiName("惠灵顿凤凰", "威灵顿凤凰",data);
    addSaiName("鹰啸联队", "豪克斯湾",data);
    addSaiName("史莫哈", "索莫哈",data);
    addSaiName("FH夏拿佐杜亚", "夏拿佐杜亚",data);
    addSaiName("弗罗瑞安娜FC", "佛罗里亚纳",data);
    addSaiName("希伯尼恩斯", "喜柏尼恩斯波拉",data);
    addSaiName("El-Kanemi Warriors", "卡尼米勇士",data);
    addSaiName("高顿", "金箭",data);
    addSaiName("华特斯", "拜维思",data);
    addSaiName("Rockmount AFC", "洛克茂",data);
    addSaiName("University College Cork AFC", "科克大学学院",data);
    addSaiName("巴塞隆拿瓜亚基尔", "巴塞隆拿SC",data);
    addSaiName("米切尔顿FC", "米切尔顿",data);
    addSaiName("阿尔哈拉穆哈拉格", "哈拉",data);
    addSaiName("圣罗拉", "绍乌拉",data);
    addSaiName("阿尔拿杰玛麦纳麦", "拿加马麦纳麦",data);
    addSaiName("同奈", "隆奈",data);
    addSaiName("珀西布万隆", "万隆",data);
    addSaiName("Binh Dinh FC", "平定",data);
    addSaiName("平陽", "贝卡麦克斯",data);
    addSaiName("Atletico de Kolkata", "加尔各答体育会",data);
    addSaiName("波希米亚人 1905", "布咸麦恩斯1905",data);
    addSaiName("阿拉伯", "阿拉巴",data);
    addSaiName("CS康斯坦丁", "CS康桑汰",data);
    addSaiName("费伦巴治", "费内巴切",data);
    addSaiName("克里夫顿维尔", "克理东维拉",data);
    addSaiName("十字軍", "库莎达斯",data);
    addSaiName("杜肯奴", "登甘宁",data);
    addSaiName("保地花高", "博塔福格RJ",data);
    addSaiName("波图格萨 RJ", "波图加沙RJ",data);
    addSaiName("桑托斯拉古纳", "圣多斯",data);
    addSaiName("斯特拉福特郡", "斯特拉特福镇",data);
    addSaiName("湯橋天使", "唐布里基",data);
    addSaiName("半岛电力", "潘尼苏拉",data);
    addSaiName("诺梅卡柳", "卡里鲁",data);
    addSaiName("棉兰", "PSMS棉兰",data);
    addSaiName("PSM望加锡", "马卡萨",data);
    addSaiName("飓风队", "乌拉坎",data);
    addSaiName("费罗维亚里亚", "费罗维里亚SP",data);
    addSaiName("蓬泰代拉", "邦特德拉",data);
    addSaiName("马杜雷拉", "米底那RJ",data);
    addSaiName("巴西佩洛塔斯", "布拉希尔佩洛塔斯RS",data);
    addSaiName("法林明高", "法林明高RJ",data);
    addSaiName("丹波SC", "甸普",data);
    addSaiName("布尔诺", "泽伯约维卡般奴",data);
    addSaiName("MFK 斯卡利察", "斯卡利卡",data);
    addSaiName("拉賈马特魯港", "阿尔拉加马特鲁港",data);
    addSaiName("高士路 RS", "高士路",data);
    addSaiName("卡希亚斯", "塞卡西亚斯RS",data);
    addSaiName("帕托邁那斯", "URT MG",data);
    addSaiName("图皮", "吐匹MG",data);
    addSaiName("Kalteng Putra FC", "卡腾浦特拉",data);
    addSaiName("拜尼亚斯", "般尼亚斯",data);
    addSaiName("ASD Borgaro Nobis", "保尔格罗诺比斯",data);
    addSaiName("Inveruno", "英维尔洛",data);
    addSaiName("瓦雷斯", "瓦雷泽",data);
    addSaiName("AS卡薩爾", "卡萨莱",data);
    addSaiName("USD 1913 Seregno", "塞雷尼奥",data);
    addSaiName("AC Bra ASD", "布拉",data);
    addSaiName("卡斯泰爾韋特羅", "卡斯泰尔韦特罗",data);
    addSaiName("福尔利", "弗利",data);
    addSaiName("Sammaurese", "桑木瑞斯",data);
    addSaiName("ASD Romagna Centro", "罗马吉纳圣图",data);
    addSaiName("Sasso Marconi", "萨索马可尼",data);
    addSaiName("A.S.D.Villabiagio", "维纳比亚几奥",data);
    addSaiName("Aquila Montevarchi", "蒙泰瓦尔基",data);
    addSaiName("Kwara Utd", "卡瓦拉联",data);
    addSaiName("阿卡瓦聯", "阿卡瓦联",data);
    addSaiName("Go Round FC", "高劳",data);
    addSaiName("卡諾支柱", "卡农皮勒斯",data);
    addSaiName("Heartland FC", "赫兰德",data);
    addSaiName("杰拉", "阿尔杰拉",data);
    addSaiName("卡兹玛", "卡斯马",data);
    addSaiName("艾吉亚", "阿亚纳帕",data);
    addSaiName("阿美利加明尼路", "美国MG",data);
    addSaiName("Oeste FC SP", "欧斯特SP",data);
    addSaiName("Sao Carlos FC SP", "索卡罗斯SP",data);
    addSaiName("Monte Azul SP", "蒙特阿苏尔SP",data);
    addSaiName("CA Penapolense SP", "佩纳博伦斯SP",data);
    addSaiName("Sertaozinho SP", "赦陶宁欧SP",data);
    addSaiName("迪斯波图SP", "波图加沙SP",data);
    addSaiName("Batatais FC SP", "霸塔苔斯SP",data);
    addSaiName("Inter De Limeira SP", "国际里梅拉SP",data);
    addSaiName("Gremio Osasco Audax SP", "格雷米奥奥萨斯库奥达柯SP",data);
    addSaiName("XV de Piracicaba SP", "皮拉西卡巴SP",data);
    addSaiName("Rio Claro SP", "里奥克拉洛SP",data);
    addSaiName("EC Taubate SP", "陶巴特SP",data);
    addSaiName("EC Agua Santa SP", "阿故圣塔SP",data);
    addSaiName("Noroeste SP", "诺罗斯特SP",data);
    addSaiName("Mogi Mirim SP", "莫奇米林SP",data);
    addSaiName("Marilia SP", "马利利亚SP",data);
    addSaiName("MAD Manthiqueira SP", "曼斯奎拉SP",data);
    addSaiName("Taboao da Serra SP", "席瑞拉SP",data);
    addSaiName("康戈迪亚齐安 SC", "孔科迪SC",data);
    addSaiName("沙佩科恩斯SC", "乔沛高恩斯SC",data);
    addSaiName("Joinville EC SC", "积安维尔SC",data);
    addSaiName("Internacional de Lages SC", "国际拉热斯SC",data);
    addSaiName("奥瓦SC", "阿瓦伊SC",data);
    addSaiName("Itumbiara GO", "伊通比亚拉GO",data);
    addSaiName("AC Goianiense GO", "戈亚尼恩斯",data);
    addSaiName("Gremio Anapolis GO", "甘美奥阿纳波利斯GO",data);
    addSaiName("彼辛度", "帕桑度PA",data);
    addSaiName("Parauapebas FC", "帕劳阿佩巴斯PA",data);
    addSaiName("Aparecidense GO", "阿帕雷西登瑟GO",data);
    addSaiName("戈亚斯GO", "奎亚斯GO",data);
    addSaiName("Uniclinic AC CE", "尤尼克立尼CE",data);
    addSaiName("福塔雷萨", "福塔雷萨CE",data);
    addSaiName("法林明高阿爾科韋迪PE", "法林明高PE",data);
    addSaiName("慕尼斯帕尔利比亚", "幕尼西波利比利亚",data);
    addSaiName("利蒙足球俱乐部", "格雷西亚",data);
    addSaiName("CA Votuporanguense SP", "沃图波兰伦斯SP",data);
    addSaiName("SP祖雲達斯", "佐云图斯SP",data);
    addSaiName("Nacional AC SP", "国民队SP",data);
    addSaiName("Sao Bernardo SP", "圣贝纳多SP",data);
    addSaiName("EC Sao Bernardo SP", "EC圣贝纳多SP",data);
    addSaiName("Portuguesa Santista SP", "波图加沙珊提斯塔SP",data);
    addSaiName("Rio Preto SP", "里奥沛图SP",data);
    addSaiName("IR克查域克", "IR雷克查域克",data);
    addSaiName("Acao MT", "阿曹MT",data);
    addSaiName("Pocone MT", "颇克勒MT",data);
    addSaiName("米那罗斯", "麦尼拉斯",data);
    addSaiName("莫纳加斯马图林", "摩纳加斯",data);
    addSaiName("麦罗波利塔诺", "麦罗波利塔诺斯",data);
    addSaiName("尤尼克里尼克CE", "尤尼克立尼CE",data);
    addSaiName("披瑟巴亚苏腊巴亚", "帕尔斯巴亚",data);
    addSaiName("匹尼", "PS TNI",data);
    addSaiName("卡斯利士堡", "基锡里士邦",data);
    addSaiName("科特迪瓦", "象牙海岸",data);
    addSaiName("华斯高", "华斯高RJ",data);
    addSaiName("班古", "邦古RJ",data);
    addSaiName("宝地花高 SP", "博塔福格SP",data);
    addSaiName("大南城主", "宋兰义安",data);
    addSaiName("南边鹰", "南国老鹰",data);
    addSaiName("伊斯顿沙伯", "伊斯特恩沙伯",data);
    addSaiName("阿尔科尔", "科赫",data);
    addSaiName("扎马雷克", "紮马雷克",data);
    addSaiName("North East United FC", "东北联",data);
    addSaiName("东方龙狮", "东方体育会",data);
    addSaiName("傑志", "杰志",data);
    addSaiName("Vila Nova GO", "维拉诺瓦GO",data);
    addSaiName("Anapolis GO", "阿纳波利斯GO",data);
    addSaiName("EC Rio Verde GO", "里奥韦尔迪GO",data);
    addSaiName("BOA EC MG", "博阿MG",data);
    addSaiName("维拉诺波利斯", "文瑞波里斯RS",data);
    addSaiName("卡尔拉", "CSA AL",data);
    addSaiName("Sampaio Correa MA", "森柏欧MA",data);
    addSaiName("CE 铁路", "费罗维里亚CE",data);
    addSaiName("ABC那托", "ABC RN",data);
    addSaiName("巴伊亚", "巴海亚BA",data);
    addSaiName("阿拉捷倫瑟", "阿拉伦斯",data);
    addSaiName("纳查雷域克", "UMF拿尔维克",data);
    addSaiName("CEOV Operario", "欧帕瑞欧MT",data);
    addSaiName("鲁沃登斯", "卢维丹斯MT",data);
    addSaiName("加拉加斯", "卡拉卡斯",data);
    addSaiName("苏利亚马拉开波", "苏里亚",data);
    addSaiName("图积兰奴斯", "祖积兰奴斯",data);
    addSaiName("萨莫拉", "萨马拉",data);
    addSaiName("英特土尔库", "英特杜古",data);
    addSaiName("TPV 坦佩雷", "TPV谭柏利",data);
    addSaiName("巴厘普山联", "巴厘联",data);
    addSaiName("波尼奥FC", "婆罗洲",data);
    addSaiName("PSPS Riau", "北乾巴鲁",data);
    addSaiName("Magwe FC", "马圭",data);
    addSaiName("贝尔雅法", "柏纳加法欧托杜瑟姆",data);
    addSaiName("希昆哈米茲拉", "石库哈米扎哈",data);
    addSaiName("加西姆舒阿夏普尔", "卡法卡斯姆沙瓦夏普尔",data);
    addSaiName("奈蒂沃特馬卡比", "奈蒂沃特",data);
    addSaiName("武里南联", "布襦姆联",data);
    addSaiName("哈拉治", "哈拉彻",data);
    addSaiName("格乔", "格索",data);
    addSaiName("萨尔高卡果阿邦", "萨尔高卡",data);
    addSaiName("梅基亚", "艾马希亚",data);
    addSaiName("阿尔阿利麦纳麦", "阿尔艾利麦纳麦",data);
    addSaiName("库巴", "高巴",data);
    addSaiName("若爾薩莫拉", "若尔萨莫拉",data);
    addSaiName("CA巴特纳", "巴特纳",data);
    addSaiName("阿尔拿达布賴米", "纳达艾布赖米",data);
    addSaiName("沙巴柏巴卡", "沙巴柏阿曼",data);
    addSaiName("阿尔伊蒂哈德吉达", "伊蒂哈德吉达",data);
    addSaiName("德桑帕拉多斯体育队", "德沙帕拉多斯",data);
    addSaiName("祖文图德尤尼达大学", "祖文图德尤尼达",data);
    addSaiName("拉腊竞技", "拉拉",data);
    addSaiName("AS马尔萨", "马撒",data);
    addSaiName("哈曼利弗", "哈曼苏塞",data);
    addSaiName("HJK赫尔辛基", "赫尔辛基",data);
    addSaiName("帕爾杜比斯", "帕都拜斯",data);
    addSaiName("塔梅卡", "塔马卡",data);
    addSaiName("莫敦提拉体育", "提尔拉",data);
    addSaiName("PS 凯米", "凯美京斯",data);
    addSaiName("AC卡亞尼", "卡杰尼",data);
    addSaiName("PAOK沙朗历基", "PAOK",data);
    addSaiName("阿尔希拉利雅德", "希拉尔",data);
    addSaiName("阿尔斯", "阿兹",data);
    addSaiName("格倫杜蘭", "格伦杜兰",data);
    addSaiName("基拿雲", "格兰坊",data);
    addSaiName("沃伦点城", "沃伦角城",data);
    addSaiName("南区足球会", "冠忠南区",data);
    addSaiName("Myawady FC", "米亚瓦迪",data);
    addSaiName("GFA FC", "GFA",data);
    addSaiName("海法", "海法夏普尔",data);
    addSaiName("费伦巴赫", "费伦巴治",data);
    addSaiName("巴扬卡拉泗水联", "巴扬卡拉",data);
    addSaiName("PSIS Semarang", "PSIS三宝珑",data);
    addSaiName("CE Santanyi", "桑塔尼",data);
    addSaiName("梅卡达尔", "梅卡达",data);
    addSaiName("阿尔萨得多哈", "萨得",data);
    addSaiName("自由洲明星队", "自由州星",data);
    addSaiName("帕拉多", "巴拉特",data);
    addSaiName("DRB 塔杰纳奈特", "DRB塔杰纳奈特",data);
    addSaiName("ES萨兹斯", "扎尔吉斯",data);
    addSaiName("高利寧", "高利宁",data);
    addSaiName("雷森迪", "雷森德RJ",data);
    addSaiName("阿故聖塔SP", "阿故圣塔SP",data);
    addSaiName("沃突普兰古恩斯SP", "沃图波兰伦斯SP",data);
    addSaiName("MC 阿尔及尔", "MC阿尔及尔",data);
    addSaiName("米拉索", "迈拉索尔SP",data);
    addSaiName("弗羅勒斯塔CE", "弗罗勒斯塔CE",data);
    addSaiName("安纳波利斯GO", "甘美奥阿纳波利斯GO",data);
    addSaiName("馬林加", "马林加PR",data);
    addSaiName("国际队圣保罗SP", "国民队SP",data);
    addSaiName("奥萨斯库奥达斯SP", "格雷米奥奥萨斯库奥达柯SP",data);
    addSaiName("巴拉那斯", "巴拉纳斯RN",data);
    addSaiName("阿美利加纳塔尔", "美国RN",data);
    addSaiName("UA Barbarense SP", "巴巴伦斯SP",data);
    addSaiName("奧克拉洛SP", "里奥克拉洛SP",data);
    addSaiName("奧斯特SP", "欧斯特SP",data);
    addSaiName("哥斯達黎加大學", "哥斯达黎加大学",data);
    addSaiName("圣保罗", "圣保罗SP",data);
    addSaiName("甘美奥诺瓦里桑蒂诺", "甘美奥诺瓦里桑蒂诺SP",data);
    addSaiName("卡洛圣佩德鲁", "卡洛",data);
    addSaiName("拉斯禾拉斯", "乌拉坎拉斯埃拉斯",data);
    addSaiName("国际立寐热SP", "国际里梅拉SP",data);
    addSaiName("CD 帕萨基纳", "帕萨奎纳",data);
    addSaiName("利斯菲体育会", "利斯菲体育会PE",data);
    addSaiName("阿福加杜斯", "阿福加杜斯PE",data);
    addSaiName("国民竞技", "国家体育会",data);
    addSaiName("伊图诺 FC", "伊图阿诺SP",data);
    addSaiName("帕拉高米纳斯", "帕哥米纳斯PA",data);
    addSaiName("馬拉巴", "马拉巴PA",data);
    addSaiName("卡尔登斯", "卡德尼斯MG",data);
    addSaiName("惠灵顿", "威灵顿队",data);
    addSaiName("比路樸", "比路朴",data);
    addSaiName("AS Montferrandaise", "摩特费安迪斯",data);
    addSaiName("科隆米尔斯", "克伦米尔",data);
    addSaiName("艾杜美图斯", "亚图米图斯",data);
    addSaiName("奧沙辛拿 B", "奥萨苏纳B队",data);
    addSaiName("Atletico Onubense", "昂本斯竞技",data);
    addSaiName("柏圖加烈特", "波图哥尼迪",data);
    addSaiName("马德里竞技 B", "马德里体育会B队",data);
    addSaiName("利亚格斯特拉", "拉高斯特拉",data);
    addSaiName("维拉利尔 B", "维拉利尔B队",data);
    addSaiName("华伦西亚 B", "华伦西亚梅斯塔拉",data);
    addSaiName("林恩斯", "林纳瑟",data);
    addSaiName("卡达根拿", "卡塔捷拿",data);
    addSaiName("UCAM穆西亚", "UCAM梅西亚",data);
    addSaiName("維拉洛尼斯", "维兰洛云斯",data);
    addSaiName("桑罗奎", "桑罗奎莱佩",data);
    addSaiName("塞维利亚 C", "西维尔C队",data);
    addSaiName("密涅瓦", "米勒瓦",data);
    addSaiName("洛尔卡", "洛尔卡B队",data);
    addSaiName("谢罗", "谢罗俱乐部",data);
    addSaiName("奥维多B", "奥维多B队",data);
    addSaiName("维多利亚奥雷拉", "欧雷拉维多利亚",data);
    addSaiName("塔拉萨", "泰拿沙",data);
    addSaiName("豪斯彼得利特", "奥斯皮塔莱特",data);
    addSaiName("切达约拉德尔瓦", "切达约拉德尔瓦莱斯",data);
    addSaiName("欧罗巴", "CE优蹂帕",data);
    addSaiName("帕拉莫斯", "帕拉玛斯",data);
    addSaiName("爱斯宾奴 B", "爱斯宾奴B队",data);
    addSaiName("利雲特體育會", "利云特体育会",data);
    addSaiName("CD莫斯托莱斯", "莫斯托莱斯",data);
    addSaiName("波苏埃洛德阿拉尔孔", "波卒埃洛",data);
    addSaiName("赫塔费 B", "基达菲B队",data);
    addSaiName("里纳瑞斯体育会", "力纳雷斯体育会",data);
    addSaiName("费古勒斯", "菲格雷斯",data);
    addSaiName("平托竞技", "平托体育会",data);
    addSaiName("华历简奴B", "瓦莱卡诺B队",data);
    addSaiName("羅斯加勒斯", "罗斯加勒斯",data);
    addSaiName("SD Ejea", "艾甲",data);
    addSaiName("布尔戈斯", "皇家布尔戈斯",data);
    addSaiName("叁蔓堤罗", "三蔓堤罗",data);
    addSaiName("CD马力诺", "马力诺",data);
    addSaiName("蒙纳斯堤", "曼纳斯特",data);
    addSaiName("AS加贝斯", "加贝斯",data);
    addSaiName("梅德宁", "梅德尼讷",data);
    addSaiName("里尔", "利尔",data);
    addSaiName("克斯奇", "中新地",data);
    addSaiName("科尔多瓦 B", "哥杜巴B队",data);
    addSaiName("圣费尔南多", "圣费尔南多埃勒诺",data);
    addSaiName("梅西亚B", "梅西亚英佩尔",data);
    addSaiName("拉尤宁", "拉尤宁CF",data);
    addSaiName("圣马田", "森玛提纳",data);
    addSaiName("奥萨斯库SP", "甘美奥奥萨斯库SP",data);
    addSaiName("维络SP", "维罗体育队SP",data);
    addSaiName("布拉希尔体育SP", "布拉希尔SP",data);
    addSaiName("維克吉", "维吉旅行者",data);
    addSaiName("Yobe Desert Stars", "约贝沙漠之星",data);
    addSaiName("里賈納", "里贾纳",data);
    addSaiName("阿尔卡西亚哈瓦利", "卡德西亚",data);
    addSaiName("阿尔阿拉毕墁所利亚", "阿拉毕科威特",data);
    addSaiName("博阿", "博阿MG",data);
    addSaiName("通布斯FC", "通布斯MG",data);
    addSaiName("彭美拉斯", "彭美拉斯SP",data);
    addSaiName("马瑟欧", "CRB AL",data);
    addSaiName("CEO FC AL", "CEO AL",data);
    addSaiName("Bahia De Feira BA", "巴海亚迪费拉BA",data);
    addSaiName("Vitoria da Conquista BA", "维多利亚大孔基斯塔BA",data);
    addSaiName("普拉斯哥野", "普拉斯哥野SC",data);
    addSaiName("基斯奧馬", "基斯奥马SC",data);
    addSaiName("泰拉登特斯", "蒂拉登特斯CE",data);
    addSaiName("奎尔巴", "古亚伯MT",data);
    addSaiName("密斯托", "密斯托MT",data);
    addSaiName("斯尔诺特", "斯尔诺特PR",data);
    addSaiName("里奧布兰克 PR", "里奥布郎库PR",data);
    addSaiName("哥里迪巴", "哥里迪巴PR",data);
    addSaiName("伊瓜苏", "伊瓜苏PR",data);
    addSaiName("Londrina PR", "隆迪那PR",data);
    addSaiName("波蒂加", "波蒂家莫索罗RN",data);
    addSaiName("圣塔库鲁", "圣塔库鲁PE",data);
    addSaiName("安托尼亞那青年", "祖文图德安图尼安",data);
    addSaiName("甘拿斯亞迪羅", "甘拿斯亚迪罗",data);
    addSaiName("圣路易斯", "圣路易斯RS",data);
    addSaiName("馬拉卡特高", "马拉卡达高",data);
    addSaiName("查莱特纳高", "查拉特南戈",data);
    addSaiName("塔奇拉", "塔赤雷",data);
    addSaiName("奥利恩特", "欧里恩特",data);
    addSaiName("廸波特斯", "迪波特斯",data);
    addSaiName("萨连斯基莫斯塔", "瑞尼斯基",data);
    addSaiName("赫维迪尼", "安卡兰",data);
    addSaiName("SAI (EZ)", "SAI加尔各答",data);
    addSaiName("河内足球俱乐部", "河内",data);
    addSaiName("Football School of India", "印度足球学校",data);
    addSaiName("波琴", "波鸿",data);
    addSaiName("科隆米爾斯", "克伦米尔",data);
    addSaiName("Stade Briochin", "博里奥庆",data);
    addSaiName("兰达杰联", "兰达吉德联",data);
    addSaiName("乌兹别克斯坦", "乌兹别克",data);
    addSaiName("TC Sports Club", "TC体育",data);
    addSaiName("清化", "FLC清化",data);
    addSaiName("蒙通联", "孟通",data);
    addSaiName("柔佛州足球俱乐部", "柔佛达罗塔晋",data);
    addSaiName("Bacabal MA", "巴卡巴尔MA",data);
    addSaiName("瑞模貝雷", "瑞模贝雷PA",data);
    addSaiName("塞克特兹亚", "耐斯茨奥纳",data);
    addSaiName("普尔城", "罗依斯顿",data);
    addSaiName("温盖特", "温葛特",data);
    addSaiName("曼彻斯特", "联曼足球会",data);
    addSaiName("斯巴坦斯", "布莱斯史巴登斯",data);
    addSaiName("艾爾佛莱頓", "阿尔费登",data);
    addSaiName("哈羅蓋特", "哈洛贾特",data);
    addSaiName("雷明頓", "莱明顿",data);
    addSaiName("维拉密雷", "维拉米特",data);
    addSaiName("桑西內納", "山斯尼纳",data);
    addSaiName("内乌肯独立", "内乌肯独立队",data);
    addSaiName("瓦斯科SC", "瓦斯科",data);
    addSaiName("北克鲁塞罗", "克鲁塞罗德尔诺特",data);
    addSaiName("柏迪亞體育", "柏迪亚体育会",data);
    addSaiName("羅卡體育", "罗卡",data);
    addSaiName("布里斯班前锋", "布里斯本前锋",data);
    addSaiName("立纳瑟", "立纳瑟SP",data);
    addSaiName("里奧普雷圖SP", "里奥沛图SP",data);
    addSaiName("民主队 GV", "迪模卡拉塔MG",data);
    addSaiName("卡斯卡韦尔", "卡斯卡韦尔PR",data);
    addSaiName("CE Uniao PR", "乌尼昂PR",data);
    addSaiName("塞爾道吉諾SP", "赦陶宁欧SP",data);
    addSaiName("奥林比亚SP", "奥林匹亚SP",data);
    addSaiName("桑堤斯塔SP", "波图加沙珊提斯塔SP",data);
    addSaiName("穆里西AL", "木瑞慈AL",data);
    addSaiName("阿里安萨", "阿利安萨圣萨尔瓦多",data);
    addSaiName("苏索纳特", "松索纳特",data);
    addSaiName("乔达路普", "ECU乔达路普",data);
    addSaiName("巴拉卡斯中央", "巴洛克斯",data);
    addSaiName("伯拉根森", "伯拉根森SP",data);
    addSaiName("阿喀巴", "阿卡巴",data);
    addSaiName("侯赛恩", "胡森伊尔比德",data);
    addSaiName("Ha Tinh", "河静",data);
    addSaiName("峴港 FC", "岘港",data);
    addSaiName("特腊帕尼", "特拉帕尼",data);
    addSaiName("佩特帕", "皮塔帕",data);
    addSaiName("索伦托 FC", "索任托",data);
    addSaiName("拉赫蒂", "拉迪",data);
    addSaiName("FC东京", "东京",data);
    addSaiName("汉诺威青年队", "汉诺威96青年队",data);
    addSaiName("法兰克福 若德斯戴", "诺德施泰特",data);
    addSaiName("莱维斯", "伊尔韦斯",data);
    addSaiName("沙辛斯堡", "萨姆士邦",data);
    addSaiName("花马拿", "花马纳",data);
    addSaiName("諾和華", "诺和华",data);
    addSaiName("马瑟维兹", "马瑟维兹英",data);
    addSaiName("阿尔贾兹拉安曼", "亚吉拉安曼",data);
    addSaiName("些斯達", "些斯达",data);
    addSaiName("阿尔玛祖雲达斯法诺", "阿尔玛祖云达斯法诺",data);
    addSaiName("阿什杜德", "阿舒多",data);
    addSaiName("桑坦德 B", "桑坦德B队",data);
    addSaiName("比亞華斯", "比雅华斯",data);
    addSaiName("Saint Pryve Saint Hilaire", "圣派维圣伊莱尔",data);
    addSaiName("利摩日", "利摩哥斯",data);
    addSaiName("圣乌尔苏拉", "圣塔乌休拉",data);
    addSaiName("埃格斯", "瓦勒伊古斯",data);
    addSaiName("Ruthin Town", "鲁思因城",data);
    addSaiName("特華莫", "特华莫",data);
    addSaiName("哥塔卡扎", "哥塔卡扎RJ",data);
    addSaiName("Nova Iguacu RJ", "诺瓦艾夸古RJ",data);
    addSaiName("里森德", "雷森德RJ",data);
    addSaiName("Madureira RJ", "米底那RJ",data);
    addSaiName("Goytacaz RJ", "哥塔卡扎RJ",data);
    addSaiName("凯撒酋长", "凯泽酋长",data);
    addSaiName("艾帕尔斯登瑟GO", "阿帕雷西登瑟GO",data);
    addSaiName("加坦哈爾", "加坦哈尔PA",data);
    addSaiName("巴巴朗斯SP", "巴巴伦斯SP",data);
    addSaiName("蒙蒂阿祖尔SP", "蒙特阿苏尔SP",data);
    addSaiName("委內瑞拉馬競", "委内瑞拉马竞",data);
    addSaiName("圣荷西", "圣乔希奥鲁罗",data);
    addSaiName("國民波托斯", "波托西",data);
    addSaiName("慕尼斯帕爾體育", "慕尼斯帕尔",data);
    addSaiName("阿爾托斯PI", "阿尔托斯PI",data);
    addSaiName("凡尼克斯", "凡尼克斯布宜诺斯艾利斯",data);
    addSaiName("烏爾基薩", "乌尔基萨",data);
    addSaiName("卡塞罗斯学生竞技", "埃斯蒂特斯卡塞罗斯",data);
    addSaiName("波魯恰門圖", "波鲁恰门图",data);
    addSaiName("维多利亚康奇斯塔BA", "维多利亚大孔基斯塔BA",data);
    addSaiName("帕特罗纳图", "佩卓纳托",data);
    addSaiName("LDU奎托", "奎托",data);
    addSaiName("圖利馬", "托利马",data);
    addSaiName("奥克兰城", "奥克兰城",data);
    addSaiName("Matonense SP", "马图尼斯SP",data);
    addSaiName("VfB欧登堡", "奥尔登堡",data);
    addSaiName("乌特波", "乌特伯",data);
    addSaiName("CD Brea", "布雷亚",data);
    addSaiName("博里奥尔", "波利奥尔",data);
    addSaiName("保查斯迅速", "拉丕多宝扎",data);
    addSaiName("塔拉韦拉", "达拉维拉瑞纳",data);
    addSaiName("UD 洛哥尼斯", "洛哥尼斯",data);
    addSaiName("皇家苏斯达B", "皇家苏斯达B队",data);
    addSaiName("希杭B", "希杭B队",data);
    addSaiName("靴格拉斯", "赫古拉斯",data);
    addSaiName("阿爾馬格羅", "阿尔马格罗CF",data);
    addSaiName("乌特雷拉", "乌特拉",data);
    addSaiName("马略卡 B", "马略卡B队",data);
    addSaiName("贝加迪诺斯", "博干蒂罗斯",data);
    addSaiName("韦斯卡", "威斯卡",data);
    addSaiName("维迪尔", "维德里尔",data);
    addSaiName("诺维尔达", "罗维达",data);
    addSaiName("格羅塔瑟尔提雅纳内斯", "葛洛塔",data);
    addSaiName("雷克查域克", "KR雷克查域克",data);
    addSaiName("奥罗拉科恰班巴", "欧若拉",data);
    addSaiName("史莊格斯特", "史庄格斯特",data);
    addSaiName("桑塔麗塔AL", "桑塔丽塔AL",data);
    addSaiName("圣马丁", "圣马丁SJ",data);
    addSaiName("威斯特曼", "约治",data);
    addSaiName("瓜毕拉蒙特罗", "葛布莉蒙泰罗",data);
    addSaiName("禾达费拉迪体育会", "沃特尔菲尔蒂",data);
    addSaiName("奇南德加", "赤纳德格",data);
    addSaiName("圣达菲联队", "圣塔菲联",data);
    addSaiName("南韩大学队", "南韩大学特选队",data);
    addSaiName("阿尔法赛利哈玛", "费萨里哈曼",data);
    addSaiName("波因科特吴哥", "波因科特",data);
    addSaiName("老挝丰田", "老挝足球倶乐部",data);
    addSaiName("苏维克", "苏怀克",data);
    addSaiName("Hilal Al Quds", "希拉尔奎德",data);
    addSaiName("列積卡", "里耶卡",data);
    addSaiName("弗卡体育", "弗卡卢RN",data);
    addSaiName("萨卡兹斯帕斯", "萨卡齐斯帕斯",data);
    addSaiName("图库曼竞技", "图库曼体育会",data);
    addSaiName("毁灭者俱乐", "底斯若耶斯",data);
    addSaiName("Cong An Nhan Dan", "人民公安",data);
    addSaiName("阿尔法赛利安曼", "阿尔费萨里安曼",data);
    addSaiName("Aspire Academy", "阿斯拜尔学院",data);
    addSaiName("伊羅尼太巴列", "提比哩亚",data);
    addSaiName("Transport United", "运输联",data);
    addSaiName("古兰尼亚松森", "瓜拉尼",data);
    addSaiName("CA 帕兰德森", "普拉腾斯",data);
    addSaiName("桑戈尔基独立足球俱乐部", "瓦伦独立",data);
    addSaiName("米爾格爾", "梅加",data);
    addSaiName("伊梅莱", "尹美利克",data);
    addSaiName("波拉斯班查奴卡", "布拉卡巴尼亚卢卡",data);
    addSaiName("蒙特維多國民隊", "蒙特维多国民队",data);
    addSaiName("摩纳哥", "图鲁兹",data);
    addSaiName("Bosque Formosa GO", "福尔摩沙DF",data);
    addSaiName("Santa Maria DF", "圣玛利亚DF",data);
    addSaiName("Real FC DF", "瑞尔DF",data);
    addSaiName("Interporto TO", "尹特普托TO",data);
    addSaiName("Real Ariquemes RO", "皇家阿里克米斯RO",data);
    addSaiName("Manaus AM", "马瑙斯AM",data);
    addSaiName("Atletico Acreano AC", "艾莱提可阿科瑞罗",data);
    addSaiName("瑟克雷大学生体育队", "瑟克雷",data);
    addSaiName("布拉格斯拉維亞", "布拉格斯拉维亚",data);
    addSaiName("安德莱赫特", "安德列治",data);
    addSaiName("阿玛祖鲁", "艾玛祖鲁",data);
    addSaiName("摩塔格", "莫塔瓜",data);
    addSaiName("阿尔阿利安曼", "阿里安曼",data);
    addSaiName("UiTM足球俱乐部", "玛拉工艺大学",data);
    addSaiName("雷尼雷克查域克", "莱尼雷克查域克",data);
    addSaiName("加玛", "加马DF",data);
    addSaiName("帕拉羅阿DF", "帕拉罗阿DF",data);
    addSaiName("巴兰基利亚青年", "小巴兰哈拉",data);
    addSaiName("卡帕提", "卡帕堤利夫",data);
    addSaiName("皮耳森", "皮尔森",data);
    addSaiName("斯塔达尔斯", "丝托达尔斯",data);
    addSaiName("郎达伊尔比德", "蓝慕沙",data);
    addSaiName("賽利亞", "赛利亚",data);
    addSaiName("关丹港", "关丹",data);
    addSaiName("UKM FC", "马来西亚国家大学",data);
    addSaiName("菲爾達聯", "菲尔达",data);
    addSaiName("红土联队", "瑞德兰茨联",data);
    addSaiName("Terengganu FC 2", "丁加奴II队",data);
    addSaiName("馬利漢姆", "马利汉姆",data);
    addSaiName("FELCRA FC", "菲尔卡拉",data);
    addSaiName("马来西亚皇家警察", "皇家警察足球俱乐部",data);
    addSaiName("柔佛州足球俱乐部2", "柔佛达罗塔晋II队",data);
    addSaiName("BSG莱比锡化工", "车米莱比锡",data);
    addSaiName("奥尔巴赫", "VfB阿尔巴赫",data);
    addSaiName("纽斯特里兹", "纽斯特里茨",data);
    addSaiName("瓦尔多夫", "阿斯多瑞亚瓦尔多夫",data);
    addSaiName("美因兹Am", "美因茨05青年队",data);
    addSaiName("阿斯特拉基尔奎", "阿斯特拉吉尔古",data);
    addSaiName("费罗", "费罗卡利尔",data);
    addSaiName("祖文图德尤尼达", "祖文图德尤尼达瓜莱瓜伊丘",data);
    addSaiName("恩斯蒂图", "联合队",data);
    addSaiName("男生竞技", "男孩竞技",data);
    addSaiName("哥達拿查拉", "芝华士",data);
    addSaiName("拉哈特", "莫阿敦提泽尔雷拉哈特",data);
    addSaiName("Shillong Lajong FC", "拉庄",data);
    addSaiName("阿尔雅莫科安曼", "雅莫科安曼",data);
    addSaiName("阿尔富吉拉", "阿尔富吉拉杜拜",data);
    addSaiName("拿華", "纳尔瓦",data);
    addSaiName("库雷萨雷", "库雷撒勒",data);
    addSaiName("弗洛里茨多尔费", "佛罗里德斯多弗尔",data);
    addSaiName("桑德尼斯", "山达勒斯",data);
    addSaiName("安戈森德", "埃格尔松斯",data);
    addSaiName("阿奇历斯", "艾切尔斯",data);
    addSaiName("阿夫朗什", "阿凡契斯",data);
    addSaiName("登卡基", "敦克尔克",data);
    addSaiName("里昂杜切爾", "里昂杜切尔",data);
    addSaiName("布羅尼", "布罗尼",data);
    addSaiName("维拉圣卡洛斯", "威勒珊卡洛斯",data);
    addSaiName("葛度爾古斯", "葛度尔古斯",data);
    addSaiName("AC巴内切亚", "巴列彻",data);
    addSaiName("莫宁", "圣地亚哥莫宁",data);
    addSaiName("裏本瑞德", "利伯泰德",data);
    addSaiName("古迪比", "KTP",data);
    addSaiName("埃格斯托夫-朗雷德", "鄂杰斯托夫兰任德",data);
    addSaiName("理文足球会", "理文",data);
    addSaiName("Lions FC", "昆士兰狮队",data);
    addSaiName("Cairns FC", "凯恩斯",data);
    addSaiName("Terengganu FC", "丁加奴",data);
    addSaiName("雪兰莪州经济发展局", "雪兰莪州发展局",data);
    addSaiName("North Queensland United", "北昆士兰联",data);
    addSaiName("Magpies Crusaders FC", "鹊十字军",data);
    addSaiName("洪卡/阿卡泰米阿", "洪卡学院",data);
    addSaiName("梦想FC", "港菁",data);
    addSaiName("珀斯SC", "佩尔斯",data);
    addSaiName("Apollon Pontou", "阿波罗波恩特欧",data);
    addSaiName("艾尔格里尼克", "阿格利尼克",data);
    addSaiName("伊斯特恩沙伯奥克兰", "伊斯特恩沙伯",data);
    addSaiName("萨尔斯堡", "红牛萨尔斯堡",data);
    addSaiName("亞塔奇", "亚塔奇",data);
    addSaiName("基亞索", "基亚索",data);
    addSaiName("河床蒙特维多", "蒙特维多河床队",data);
    addSaiName("芬斯", "凡尼克斯孟特维迪欧",data);
    addSaiName("Club Atletico Torque", "图尔克",data);
    addSaiName("Deportivo Binacional", "彼纳茨纳勒",data);
    addSaiName("坎圖勞", "坎图劳",data);
    addSaiName("雷昂內斯 FC", "利昂内斯",data);
    addSaiName("卡尔达斯", "卡尔打斯",data);
    addSaiName("贾奎斯科尔多巴", "贾奎斯科尔多瓦",data);
    addSaiName("葛拉兹拉斯", "皇家加西拉索",data);
    addSaiName("艾域加多", "依维加杜",data);
    addSaiName("维塔克联队", "怀塔克雷联",data);
    addSaiName("布伦瑞克Am", "布伦瑞克青年队",data);
    addSaiName("汉堡 AM", "汉堡青年队",data);
    addSaiName("柏林AK", "柏林讷AK07",data);
    addSaiName("FSV 路肯瓦德", "路肯瓦德",data);
    addSaiName("鲍特琛", "巴迪莎",data);
    addSaiName("杰德劳", "捷德鲁",data);
    addSaiName("伊瓦顿", "爱华顿比尼亚德尔马",data);
    addSaiName("冠忠南区", "南区足球会",data);
    addSaiName("乌丁根05", "乌丁根",data);
    addSaiName("波洛克瓦尼", "波罗克瓦尼城",data);
    addSaiName("P Iirot YJ", "伊洛特YJ",data);
    addSaiName("VIFK Vaasa", "维夫克",data);
    addSaiName("华列达", "瓦莱塔",data);
    addSaiName("巴仁FC", "巴尔赞",data);
    addSaiName("基尔禾", "切沃",data);
    addSaiName("圣帕特里克", "圣巴特里",data);
    addSaiName("Internacional San Miguel de Allende", "圣米格尔德阿连德",data);
    addSaiName("聖馬田學院", "圣马丁",data);
    addSaiName("阿亚库乔 FC", "阿亚库乔",data);
    addSaiName("強者", "邦明",data);
    addSaiName("阿拉皮拉卡", "ASA AL",data);
    addSaiName("若茵维莱SC", "积安维尔SC",data);
    addSaiName("國際體育會SC", "国际拉热斯SC",data);
    addSaiName("波多卡贝罗", "卡贝略港学院",data);
    addSaiName("波图加沙", "波图加沙足球俱乐部",data);
    addSaiName("艾斯图第安特梅里", "艾斯图第安特",data);
    addSaiName("埃斯蒂特斯", "学生队",data);
    addSaiName("弗兰科瓜拉尼竞技", "古兰尼安东尼奥弗兰科",data);
    addSaiName("古铁雷斯足球俱乐部", "古铁瑞斯",data);
    addSaiName("布卡拉曼格", "布卡拉曼加体育会",data);
    addSaiName("桑塔尼體育", "桑坦尼",data);
    addSaiName("费布雷诺", "弗布罗",data);
    addSaiName("利马联盟", "阿里萨利马",data);
    addSaiName("瓦迪维亚", "瓦尔迪维亚",data);
    addSaiName("保衛者隊", "德丰索体育队",data);
    addSaiName("阿特纳斯", "阿特那斯珊卡洛斯",data);
    addSaiName("圣达菲波哥大", "圣塔菲",data);
    addSaiName("羅薩裏奧體育", "罗沙里奥体育",data);
    addSaiName("国民会亚松森", "那西昂诺",data);
    addSaiName("茨高", "奇科",data);
    addSaiName("巴里科士邦", "巴里科斯士邦",data);
    addSaiName("康戈迪亞齊安", "康戈迪亚齐安",data);
    addSaiName("K.奧芬巴查", "奥芬巴查踢球者",data);
    addSaiName("金斯頓拿", "基士多尼亚",data);
    addSaiName("独立队足球俱乐部", "独立FBC",data);
    addSaiName("万卡约", "万卡",data);
    addSaiName("U关丹港", "关丹",data);
    addSaiName("丁加奴足球俱乐部", "丁加奴",data);
    addSaiName("Felcra FC", "菲尔卡拉",data);
    addSaiName("Nacional FC AM", "国民队AM",data);
    addSaiName("巴西人", "布拉希莱恩斯DF",data);
    addSaiName("Southside Eagles FC", "南国老鹰",data);
    addSaiName("瑟蘭迪亚DF", "瑟兰迪亚DF",data);
    addSaiName("摩吉米林SP", "莫奇米林SP",data);
    addSaiName("CA Itapemirim ES", "伊塔佩米林ES",data);
    addSaiName("艾斯哥比度", "埃斯科贝多",data);
    addSaiName("SD Sparta TO", "斯巴达TO",data);
    addSaiName("聖瑞蒙度RR", "圣雷姆恩多RR",data);
    addSaiName("欧帕瓦", "奥帕华",data);
    addSaiName("卡杜華斯", "GKS卡托威斯",data);
    addSaiName("洛斯基尔德", "洛斯基德",data);
    addSaiName("马纳", "维也纳新城",data);
    addSaiName("維圖斯維羅納", "维图斯维罗纳",data);
    addSaiName("US Pianese", "匹安斯",data);
    addSaiName("Matelica Calcio", "马泰利卡",data);
    addSaiName("A.S.D. San Donato Tavarnelle", "圣多纳托",data);
    addSaiName("莫斯科戴拿模", "迪纳摩莫斯科",data);
    addSaiName("USD Audace Cerignola", "奥达彻切里尼奥拉",data);
    addSaiName("ASD Monticelli", "蒙蒂切利",data);
    addSaiName("曼彻斯特联", "曼联",data);
    addSaiName("艾马赞", "艾尔玛善",data);
    addSaiName("阿尔奥鲁巴", "阿尔欧鲁巴苏瑞",data);
    addSaiName("尼日爾托納多斯", "尼日尔托纳多斯",data);
    addSaiName("Bolamense DF", "博拉门瑟DF",data);
    addSaiName("阿尔曼西亚贝尼哈山", "曼序亚特",data);
    addSaiName("阿曼FC", "阿曼俱乐部",data);
    addSaiName("阿纳斯尔", "阿尔纳斯",data);
    addSaiName("高隆", "科隆竞技",data);
    addSaiName("PTT羅勇", "PTT罗勇足球俱乐部",data);
    addSaiName("羅勇", "罗勇",data);
    addSaiName("卡比利奧馬卡比", "艾罗尼马卡比",data);
    addSaiName("比卡塔哈亚登", "吉尔波亚英",data);
    addSaiName("亞夫涅", "亚夫涅英",data);
    addSaiName("姆牙比", "米亚尔比",data);
    addSaiName("哈米亚", "哈瑞亚",data);
    addSaiName("阿拉畢 (阿联酋)", "阿拉毕欧姆古温",data);
    addSaiName("UII奇薩", "欧伦萨可",data);
    addSaiName("Gold Coast United", "黄金海岸联",data);
    addSaiName("瓦滕沙伊德 09", "华登舒特",data);
    addSaiName("Global Cebu FC", "环球宿雾",data);
    addSaiName("Hantharwady United", "汉达瓦底联",data);
    addSaiName("标准流浪", "香港流浪足球会",data);
    addSaiName("OFI", "OFI克雷迪",data);
    addSaiName("泰国皇家空军", "空军中央队",data);
    addSaiName("素可泰FC", "素可泰",data);
    addSaiName("泰軍聯", "泰军联",data);
    addSaiName("農布阿皮查亞", "农布阿皮查亚",data);
    addSaiName("Leones Vegetarianos", "素狮",data);
    addSaiName("曼谷联合队", "曼谷联",data);
    addSaiName("施利马", "施利马流浪者",data);
    addSaiName("纳沙尔狮队", "纳克萨尔雄狮",data);
    addSaiName("卡拉巴克阿格达姆", "卡拉巴克",data);
    addSaiName("亚美利加足球会", "阿美利加会",data);
    addSaiName("柏斯體育隊", "柏斯体育队",data);
    addSaiName("圣菲利普联", "圣菲利浦联",data);
    addSaiName("罗赫林弗尔克林根", "罗赫林弗尔克林",data);
    addSaiName("贺芬咸Am", "贺芬咸青年队",data);
    addSaiName("乌尔梅", "SSV乌尔姆",data);
    addSaiName("曲克城", "科克城",data);
    addSaiName("穆萨", "穆莎",data);
    addSaiName("皇家马德里B队", "皇家马德里卡斯蒂亚",data);
    addSaiName("艾高亞諾", "艾高亚诺",data);
    addSaiName("比拉拉达", "佩拉拉达赫罗纳B队",data);
    addSaiName("格拉纳达 B", "格拉纳达B队",data);
    addSaiName("切尔达B", "切尔达B队",data);
    addSaiName("莫斯科卡赞卡火车头", "卡赞卡火车头",data);
    addSaiName("迪尼伯莫吉廖夫", "迪尼普莫吉莱夫",data);
    addSaiName("克拉斯诺达尔 2", "克拉斯诺达尔II队",data);
    addSaiName("夏卡-j/HJS/YJ", "夏卡哈马YJ",data);
    addSaiName("拉查斯馬", "纳空叻差斯玛",data);
    addSaiName("拉納維", "泰国皇家海军",data);
    addSaiName("史沙克特", "斯萨克",data);
    addSaiName("孔克恩", "赫恩柯恩",data);
    addSaiName("帕塔亚联", "芭堤雅联",data);
    addSaiName("巴蜀基利", "巴蜀",data);
    addSaiName("特羅警察", "特罗警察",data);
    addSaiName("Asante Kotoko SC", "阿散蒂科托科",data);
    addSaiName("CARA Brazzaville", "布拉扎维尔",data);
    addSaiName("奥林匹克萨非", "奥林比亚萨非",data);
    addSaiName("埃努古流浪者", "埃努古流浪",data);
    addSaiName("卡拉米勇士", "卡尼米勇士",data);
    addSaiName("拉辛卡薩布蘭卡", "拉辛卡萨布兰卡",data);
    addSaiName("波帕扬大学", "珀帕妍",data);
    addSaiName("Olympic Real De Bangui", "皇家奥林匹克",data);
    addSaiName("IF Magni", "马格力",data);
    addSaiName("候卡尔夏拿佐杜亚", "候卡尔",data);
    addSaiName("Libertad", "利伯泰德",data);
    addSaiName("蒙特维多竞技", "蒙特维多竞赛会",data);
    addSaiName("丹奴比", "丹纽比奥",data);
    addSaiName("珮雷拉", "佩雷拉",data);
    addSaiName("福塔雷绍查", "福塔雷扎CEIF",data);
    addSaiName("慕尼奇博尔立米诺", "慕尼崎柏尔立米诺",data);
    addSaiName("水晶竞技队", "水晶竞技",data);
    addSaiName("哥杜雷亚图卢阿", "科图鲁阿",data);
    addSaiName("River Plate Montevideo", "蒙特维多河床队",data);
    addSaiName("La Equidad", "拉伊奎达德",data);
    addSaiName("马拉顿", "莫拉松",data);
    addSaiName("CSM雅西", "拉斯理工体育会",data);
    addSaiName("圣马丁德图车曼", "圣马丁德图库曼",data);
    addSaiName("塞雷那", "希金斯",data);
    addSaiName("阿尔阿赫德", "赫德",data);
    addSaiName("阿尔紥瓦阿", "扎乌拉",data);
    addSaiName("阿尔贾徐大马士革", "贾伊什",data);
    addSaiName("AEL利馬斯素爾", "AEL利马斯素尔",data);
    addSaiName("利亞競技", "利亚竞技",data);
    addSaiName("雷霍沃特夏普爾", "雷霍沃特夏普尔",data);
    addSaiName("咸侖斯巴坦", "咸仑斯巴坦",data);
    addSaiName("格齐拉联", "格兹拉联",data);
    addSaiName("森格利亞競技", "森格莱阿",data);
    addSaiName("科美西歐", "科美西欧",data);
    addSaiName("迪亞茲", "迪亚兹",data);
    addSaiName("本國聯队", "内政联队",data);
    addSaiName("全北现代汽车", "全北现代",data);
    addSaiName("阿尔瓦赫达大马士革", "阿尔瓦达",data);
    addSaiName("BW林茨", "布劳伟斯林兹",data);
    addSaiName("莫多瓦耶", "摩尔多维亚",data);
    addSaiName("Al Ansar Beirut", "阿萨尔麦地那",data);
    addSaiName("恩拿基亚", "卢兹恩吉亚",data);
    addSaiName("阿尔纳沙阿尔费尔瓦尼耶", "阿尔纳赛尔费尔瓦尼耶",data);
    addSaiName("Cwmamman United", "库马曼联",data);
    addSaiName("UTC卡哈马卡", "卡加马卡",data);
    addSaiName("里加足球俱乐部", "里加",data);
    addSaiName("斯库皮", "史酷匹",data);
    addSaiName("潘多夫學院", "潘德维学院",data);
    addSaiName("斯肯迪加", "舒肯迪捷",data);
    addSaiName("华达", "华达斯科普里",data);
    addSaiName("拉博特尼基", "拉布历基",data);
    addSaiName("雷诺瓦", "连诺华",data);
    addSaiName("玻比达派纳", "波贝达",data);
    addSaiName("比利斯特", "彼里史特",data);
    addSaiName("ASD Francavilla", "ASD法安卡维拉",data);
    addSaiName("艾西利亚尼", "阿奇雷亚莱",data);
    addSaiName("ACR墨西拿", "麦斯纳",data);
    addSaiName("AL科威特", "阿尔科威特",data);
    addSaiName("迪法", "DHJ哈斯沙尼亚",data);
    addSaiName("奥林比亚华利加", "柯里加",data);
    addSaiName("IR 丹吉尔", "利替翰丹吉尔",data);
    addSaiName("新英倫革命", "新英伦革命",data);
    addSaiName("達拉斯燃燒", "达拉斯",data);
    addSaiName("拉克霍尔", "拉卡海尔",data);
    addSaiName("萨克达顿涅茨克", "萨克达",data);
    addSaiName("拉卡塔米亚", "拉卡塔麦斯",data);
    addSaiName("Sturt Lions", "斯图特狮子",data);
    addSaiName("索尔兹伯里美国", "塞利斯贝瑞联",data);
    addSaiName("诺亚伦加", "诺仑加联",data);
    addSaiName("Fulham United FC", "富勒姆联",data);
    addSaiName("伊斯特恩獅隊", "东方狮子",data);
    addSaiName("华勒比市", "华勒比",data);
    addSaiName("丹德農市", "丹德农城",data);
    addSaiName("比勒费尔德", "恩高斯达",data);
    addSaiName("艾維達堡", "艾维达堡",data);
    addSaiName("克拉科维亚克拉科夫", "克拉科维亚",data);
    addSaiName("科麥立克", "立麦立克",data);
    addSaiName("雅丹纳博足球俱乐部", "亚大纳保",data);
    addSaiName("苏杜瓦马里扬泊列", "苏杜瓦",data);
    addSaiName("查纳特", "查英特贺纳比尔",data);
    addSaiName("艾塔", "伊塔尔大特尔诺沃",data);
    addSaiName("PFC瑟特曼維里索菲亞", "瑟特曼维里索菲亚",data);
    addSaiName("亞特蘭大聯隊", "亚特兰大联",data);
    addSaiName("克魯里佩", "柯鲁里普AL",data);
    addSaiName("摩托雷爾沖擊", "蒙特利尔冲击",data);
    addSaiName("休斯顿戴拿模", "侯斯顿戴拿模",data);
    addSaiName("阿德莱德彗星", "阿德莱科梅兹",data);
    addSaiName("托列斯比卡拉", "西托任比卡拉",data);
    addSaiName("Wide Bay Buccaneers", "广湾海盗",data);
    addSaiName("白城", "白城伍德维尔",data);
    addSaiName("Sagaing United FC", "实皆联",data);
    addSaiName("塔比歷斯", "塔比历斯",data);
    addSaiName("兰德斯", "兰达斯",data);
    addSaiName("乔科品斯", "乔科平所达",data);
    addSaiName("法瑞伊", "费里塔比",data);
    addSaiName("达尔库达", "达库德",data);
    addSaiName("FC Ahal", "阿哈尔",data);
    addSaiName("帕克斯", "佩克斯",data);
    addSaiName("多伦多FC", "多伦多",data);
    addSaiName("阿尔沙巴柏麦纳麦", "沙巴柏麦纳麦",data);
    addSaiName("多罗吉", "都罗基",data);
    addSaiName("OFK佩特罗瓦", "派佐瓦克",data);
    addSaiName("蘇積斯卡", "尼卡斯克",data);
    addSaiName("Williamsville AC", "威廉斯维尔",data);
    addSaiName("斯塔德马里恩", "史塔德马里安巴马科",data);
    addSaiName("杜那卡亞", "瓦茨",data);
    addSaiName("Ahi Acre", "阿利阿克雷",data);
    addSaiName("Ihud Bnei Majd Al Krum", "伊呼比尼马德克鲁姆",data);
    addSaiName("迪卓恩", "迪安",data);
    addSaiName("海尔欧 (苏丹)", "希拉尔恩图曼",data);
    addSaiName("LISCR FC", "LISCR蒙罗维亚",data);
    addSaiName("Young Buffaloes", "年轻水牛",data);
    addSaiName("Eding Sport FC", "伊丁体育",data);
    addSaiName("艾斯普", "埃斯波",data);
    addSaiName("史达", "斯达",data);
    addSaiName("Aduana Stars FC", "阿杜亚纳",data);
    addSaiName("Al Tahaddi", "塔哈迪",data);
    addSaiName("AS Real Bamako", "皇家巴马科",data);
    addSaiName("AS Togo Port", "多哥港",data);
    addSaiName("AC勒奥帕德", "AC罗帕德",data);
    addSaiName("米莫萨", "ASEC密模沙",data);
    addSaiName("Buffles du Borgou FC", "博尔古水牛",data);
    addSaiName("ASAC Concorde", "康戈德",data);
    addSaiName("AC Rezzato", "雷扎托",data);
    addSaiName("Ciserano", "奇塞拉诺",data);
    addSaiName("BFC 西奧福克", "斯欧福克",data);
    addSaiName("基斯柏斯汉维特", "汉维德",data);
    addSaiName("Generation Foot", "根内拉逊",data);
    addSaiName("Zulte Waregem", "威尔郡",data);
    addSaiName("阿爾馬裏克", "阿尔梅瑞克",data);
    addSaiName("Township Rollers FC", "托姆斯普",data);
    addSaiName("AS Otoho", "奥托贺",data);
    addSaiName("Banjul Hawks FC", "班珠尔",data);
    addSaiName("Fram/Ulfarnir", "弗雷姆乌法利尔",data);
    addSaiName("堪萨斯巫师", "肯萨斯城体育会",data);
    addSaiName("奥拉弗斯维", "维吉欧拉维克",data);
    addSaiName("列弗宁", "利汾瑞",data);
    addSaiName("TSV哈特堡格", "哈特堡格",data);
    addSaiName("因斯布鲁克瓦克尔", "华卡迪路",data);
    addSaiName("古利姆", "吉列尔莫布朗",data);
    addSaiName("诺夫克特城市SC", "诺斯科特市",data);
    addSaiName("比羅", "比罗",data);
    addSaiName("利贝雷茨", "利巴域",data);
    addSaiName("UT亞拉德", "UTA亚拉德",data);
    addSaiName("塞林西尼", "塞林西尼学院",data);
    addSaiName("潘杜歷", "潘杜历",data);
    addSaiName("梅塔洛格布斯", "梅塔罗洛布斯",data);
    addSaiName("蒂米索拉", "普利塔力卡蒂米甚瓦拉",data);
    addSaiName("索尔亚", "柔亚",data);
    addSaiName("华萨斯布达佩斯", "华萨斯",data);
    addSaiName("沃特福德", "屈福特",data);
    addSaiName("雷法拉竞技", "艾朗迪考瑞法拉",data);
    addSaiName("橫濱飛翼", "横滨",data);
    addSaiName("讚岐烏冬", "卡马塔马尔赞岐",data);
    addSaiName("冈山绿雉", "冈山雉鸡",data);
    addSaiName("愛媛FC", "爱媛",data);
    addSaiName("雷法山口", "雷诺法山口",data);
    addSaiName("熊本", "熊本深红",data);
    addSaiName("甲府维费瑞", "甲府风林",data);
    addSaiName("Lahti YJ", "拉迪YJ",data);
    addSaiName("弗恩拉布拉达", "富恩拉布雷达",data);
    addSaiName("斯巴达克苏博蒂察", "斯巴达克苏波迪加",data);
    addSaiName("里澤士邦", "里泽士邦",data);
    addSaiName("拜仁慕尼黑青年队", "贺芬咸青年队",data);
    addSaiName("艾希斯特", "艾禾斯堡",data);
    addSaiName("科隆Am", "科隆青年队",data);
    addSaiName("薩拉米斯", "萨拉米斯",data);
    addSaiName("奥兰多海盗队", "奥兰多海盗",data);
    addSaiName("保罗塞斯度", "塞斯托",data);
    addSaiName("比士托爾斯", "比士托尔斯",data);
    addSaiName("馬里博爾", "马里博尔",data);
    addSaiName("诺尔比", "诺比",data);
    addSaiName("赫根", "哈肯",data);
    addSaiName("卡帕茨", "卡帕",data);
    addSaiName("泽卡", "兹尔卡",data);
    addSaiName("奧林贝贾德", "奥林比查",data);
    addSaiName("佩利根", "肖结",data);
    addSaiName("特克尼克", "泰尼科",data);
    addSaiName("思罗图尔雷克雅维克", "图罗杜尔",data);
    addSaiName("普罗雷索", "普罗格雷索",data);
    addSaiName("巴格達空軍", "巴格达空军",data);
    addSaiName("巴兰基利亚", "巴瑞库拉",data);
    addSaiName("屈達福", "屈福特",data);
    addSaiName("士特宁", "艾洛亚",data);
    addSaiName("泰拿尼斯", "塔勒雷斯",data);
    addSaiName("阿華加德", "艾文嘉德",data);
    addSaiName("達利亞特夏普爾", "达利亚阿卡梅夏普尔",data);
    addSaiName("馬卡比阿力伊斯爾", "马卡比阿力伊斯尔",data);
    addSaiName("恩菲尔德镇", "恩菲尔德城",data);
    addSaiName("斯彭尼穆尔城", "史佩尼摩尔",data);
    addSaiName("南后", "南後",data);
    addSaiName("亞布嶽夫", "亚布岳夫",data);
    addSaiName("艾比安士特寧", "艾比安士特宁",data);
    addSaiName("瑞迪契", "雷笛特",data);
    addSaiName("格洛斯特城", "古鲁斯特城",data);
    addSaiName("维斯顿", "威斯通",data);
    addSaiName("聖阿爾班斯", "圣阿尔班斯",data);
    addSaiName("比路查甸", "贝卢雅尔丁PE",data);
    addSaiName("EC Tupy", "图匹ES",data);
    addSaiName("Cameta PA", "卡梅塔PA",data);
    addSaiName("科羅拉多急流", "科罗拉多急流",data);
    addSaiName("班南特斯叶里温", "巴纳特斯",data);
    addSaiName("比尔舒华夏普尔", "比尔舒华哈索罗沙夏普尔",data);
    addSaiName("FC Hermannstadt", "赫曼施塔特",data);
    addSaiName("Cibao FC", "希巴欧",data);
    addSaiName("全南龙队", "全罗南道天龙",data);
    addSaiName("FC 汉城", "首尔",data);
    addSaiName("艾拉华特", "阿拉特",data);
    addSaiName("简萨沙", "卡磐",data);
    addSaiName("美狄亞", "美狄亚",data);
    addSaiName("西雅图音速", "西雅图音响",data);
    addSaiName("素巴拉甸奴DF", "索布拉迪纽DF",data);
    addSaiName("佩斯奎尔拉", "佩斯奎尔拉PE",data);
    addSaiName("摩托聖路易", "摩托MA",data);
    addSaiName("聖塔奎特瑞", "圣塔奎特瑞MA",data);
    addSaiName("紐約红牛", "纽约红牛",data);
    addSaiName("帕斯科華倫", "帕斯科华伦",data);
    addSaiName("卡瓦利尔斯", "绿色古利",data);
    addSaiName("班特列格林斯", "班特列",data);
    addSaiName("西阿德莱德海拉斯", "西阿德莱",data);
    addSaiName("札幌冈萨多", "北海道札幌冈萨多",data);
    addSaiName("安納利", "安奈尔",data);
    addSaiName("杜旺 FC", "图旺",data);
    addSaiName("Park Ridge", "帕克里奇",data);
    addSaiName("Oxley United", "奥克斯利联",data);
    addSaiName("Caboolture FC", "卡布尔彻",data);
    addSaiName("格蘭", "格兰奇",data);
    addSaiName("大邱FC", "大邱",data);
    addSaiName("金斯敦城", "金士顿城",data);
    addSaiName("FC岐阜", "岐阜",data);
    addSaiName("富川FC", "富川",data);
    addSaiName("安阳", "安养",data);
    addSaiName("江原FC", "江原",data);
    addSaiName("重庆力帆", "重庆当代力帆",data);
    addSaiName("休城", "休姆",data);
    addSaiName("士特宁狮队", "史崔林狮队",data);
    addSaiName("杜伊斯堡", "奥斯拿布克",data);
    addSaiName("纽伦堡", "海登海默",data);
    addSaiName("柏多華", "柏多华",data);
    addSaiName("阿尔布加亚安曼", "巴夸",data);
    addSaiName("波德比錫奇斯", "保德比斯基",data);
    addSaiName("歐斯泰恩", "奥尔什丁",data);
    addSaiName("博雷斯拉夫", "博莱斯拉夫",data);
    addSaiName("塔林纳加雷", "卡勒威",data);
    addSaiName("度泽", "度泽ES",data);
    addSaiName("Rio Branco VN", "里奥布郎库ES",data);
    addSaiName("帕爾納伊巴", "帕纳海柏PI",data);
    addSaiName("利物浦蒙得維的亞", "利物浦蒙特维多",data);
    addSaiName("费城联盟", "费城联合",data);
    addSaiName("亞特蘭特", "亚特兰特",data);
    addSaiName("奧蘭多市", "奥兰多市",data);
    addSaiName("栃木SC", "槴木SC",data);
    addSaiName("庆尚南道", "庆南",data);
    addSaiName("Acacia Ridge", "阿卡西亚岭",data);
    addSaiName("首尔衣恋", "首尔埃兰",data);
    addSaiName("Sunshine Coast Wanderers", "阳光海岸流浪者",data);
    addSaiName("貝賽聯", "贝赛联",data);
    addSaiName("昆士兰大学", "昆士兰科技大学",data);
    addSaiName("Brisbane Knights", "布里斯班骑士",data);
    addSaiName("克拉斯诺亚斯克", "克拉斯诺亚尔斯克",data);
    addSaiName("度莫斯", "唐姆斯基",data);
    addSaiName("古班克拉斯诺达", "库班",data);
    addSaiName("埃斯比约", "艾斯堡",data);
    addSaiName("加尔斯哥登堡", "瓂斯哥德堡",data);
    addSaiName("赛雷卡苏德", "西里安斯卡",data);
    addSaiName("春武里省", "春武里",data);
    addSaiName("羅切拉", "罗切拉",data);
    addSaiName("阿玛瓂厄", "阿玛盖尔",data);
    addSaiName("托爾阿庫雷裏", "托尔阿库瑞",data);
    addSaiName("基多天主教大学", "卡托利卡基多",data);
    addSaiName("耶路撒冷比达", "比达耶路撒冷",data);
    addSaiName("CE奥尔豪AL", "CEO AL",data);
    addSaiName("巴伊亚德BA", "巴海亚迪费拉BA",data);
    addSaiName("中央SC", "中央体育会PE",data);
    addSaiName("沙古尔罗", "沙古尔罗PE",data);
    addSaiName("史特賈納", "斯塔尔南",data);
    addSaiName("Los Angeles FC", "洛杉矶",data);
    addSaiName("查卡瑞塔青年", "查卡塔青年队",data);
    addSaiName("溫哥華白帽", "温哥华白帽",data);
    addSaiName("艾瑞布尼", "埃尔布尼",data);
    addSaiName("卡磐B队", "卡磐II队",data);
    addSaiName("當薩勒", "当萨勒",data);
    addSaiName("提拉哈卡默爾夏普爾", "提拉哈卡默尔夏普尔",data);
    addSaiName("路达", "鲁达瓦伦",data);
    addSaiName("Hwaepul SC", "火炬体育团",data);
    addSaiName("阿莱奥斯", "阿来奥什",data);
    addSaiName("环球宿雾足球会", "环球宿雾",data);
    addSaiName("名古屋八鲸", "名古屋鲸鱼",data);
    addSaiName("拉迪恩", "新瑞登特",data);
    addSaiName("伊斯特格拉尔", "伊斯蒂克罗尔",data);
    addSaiName("科坎 1912", "科坎",data);
    addSaiName("索菲亞中央陸軍", "索菲亚中央陆军",data);
    addSaiName("阿曉斯", "阿晓斯",data);
    addSaiName("阿勞", "阿劳",data);
    addSaiName("马杜雷拉RJ", "米底那RJ",data);
    addSaiName("横滨体育", "横滨SCC",data);
    addSaiName("布格勒斯特祖雲斯", "布格勒斯特祖云达斯",data);
    addSaiName("WSG华顿斯", "华登斯",data);
    addSaiName("馬特斯", "马特斯",data);
    addSaiName("卡宾提利", "卡宾迪利",data);
    addSaiName("科布漫步者隊", "科布漫步者队",data);
    addSaiName("萊茨納", "莱茨纳",data);
    addSaiName("托斯诺", "图斯诺",data);
    addSaiName("鲁宾喀山", "鲁宾卡赞",data);
    addSaiName("弗里代克-米斯泰克", "弗雷德克",data);
    addSaiName("光州 FC", "光州",data);
    addSaiName("史賓威白鷹", "史宾威白鹰",data);
    addSaiName("波克海尔联", "波克海尔",data);
    addSaiName("Wide Bay Buccaneers", "广湾海盗",data);
    addSaiName("聖彼德斯堡戴拿模", "圣彼德斯堡戴拿模",data);
    addSaiName("A.P.I.A萊洽德", "APIA莱洽德",data);
    addSaiName("马可尼", "马柯尼",data);
    addSaiName("悉尼联盟58", "悉尼联58",data);
    addSaiName("丹德農迅雷", "丹德农迅雷",data);
    addSaiName("阿德莱德奥运", "阿德莱德奥林匹克",data);
    addSaiName("悉尼 FC (青年队)", "悉尼(青年)",data);
    addSaiName("夏克悉尼", "哈柯亚东悉尼市",data);
    addSaiName("安郅", "安芝",data);
    addSaiName("朗福特", "朗福特城",data);
    addSaiName("塔格雷", "堤格雷",data);
    addSaiName("芝加哥火燄", "芝加哥火焰",data);
    addSaiName("奥特 BK", "奥特",data);
    addSaiName("特羅素", "特罗素",data);
    addSaiName("卡坦尼亞", "卡坦尼亚",data);
    addSaiName("基爾梅斯", "基尔梅斯",data);
    addSaiName("杜希達聯", "杜希达联",data);
    addSaiName("奧斯積克", "奥斯积克",data);

    addSaiName("深圳球会", "深圳佳兆业",data);
    addSaiName("HB高治", "HB科治",data);
    addSaiName("巴布安特 IF", "巴布安特",data);
    addSaiName("卡斯魯厄", "卡斯鲁厄",data);
    addSaiName("阿尔托那", "阿尔托纳",data);
    addSaiName("BSV施瓦茲維斯雷登", "雷登",data);
    addSaiName("杜塞尔多夫Am", "杜塞尔多夫青年队",data);
    addSaiName("亞琛", "亚琛",data);

    addSaiName("阿特雷约", "阿特劳",data);
    addSaiName("艾馬迪", "凯拉特艾马迪",data);
    addSaiName("FC Kyzylzhar", "彼得罗巴甫洛夫斯克",data);
    addSaiName("卡萨尔克孜勒奥尔达", "卡萨尔",data);
    addSaiName("阿卡托比", "阿克托比",data);
    addSaiName("捷迪苏塔迪科根", "斯咸迪苏",data);
    addSaiName("杜保爾", "杜保尔",data);
    addSaiName("达兹巴雷拉", "芭雷拉",data);
    addSaiName("安察利克乌拉尔", "安察利克",data);
    /*********************打印数量********************/
    let counter = 0;
    for(let key in data) counter++;
    console.log("已匹配球队数量:"+counter);
    return data;
}

let AddData = {
    getSaiList:getSaiList,
};

module.exports =  AddData;